### ISSUE TITLE
`{direction}` is missed in a path of `get_txs_by_direction` method of swagger file

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1029]
If the path named just `/txs` instead of `/txs/{direction}` then `swagger-client` omits `direction` parameter.

**Comment by thepiwo** [comment]
can you provide a PR maybe? Generally I guess its easier for these small docs only changes. But I think we made a bunch of changes from 1.28.1 to 1.29.1 already, maybe you are accessing the old version still? (1.29.1 is not deployed to prod yet)

**Comment by davidyuk** [comment]
it was fixed in 11e9438b6127219ce23523bf1214516a26ddeda3
