### ISSUE TITLE
Add missing transaction details data for channels

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/ae_mdw#1032]
Currently not all transactions data is returned from `/v2/txs/:transactionId` endpoint.

It would be useful to include the following data for these "Channel" transactions types to have a more detailed overview of these transaction types:

ChannelCreateTx:
- Sent by

ChannelCloseMutualTx:
- Responder
- Initiator

ChannelCloseSoloTx:
- Round
- Initiator
- Initiator amount
- Responder
- Responder amount

ChannelSlashTx:
- Round

ChannelSettleTx:
- Initiator
- Initiator amount

ChannelSnapshotSoloTx:
- Round
- Initiator
- Initiator amount
- Responder
- Responder amount

ChannelForceProgressTx:
- Initiator 
- Initiator amount
- Responder 
- Responder amount

**Comment by sborrazas** [comment]
I've now added the `/v2/channels/:id` page for being able to retrieve most of this information. The round number updated on every snapshot and slash transaction is still missing. It will be added by @jyeshe in the future

**Comment by jyeshe** [comment]
@michele-franchi I am closing this considering it done as the issue involving channels is for another reason. The fields that you will find missing are for the reasons:
- `ChannelCreateTx`: If there is no particular case missing the sender would be the initiator (after the creation, other transactions could be initiated by delegates). Actually the sender could be by someone `paying_for` the channel creation but it would be associated already in `/txs`. Free to open a specific issue if there is a specific requirement to make any additional relation with `paying_for`, `ga_meta` or other sender context. 
- `ChannelCloseSoloTx`, `ChannelSnapshotSoloTx` and `ChannelForceProgressTx`: The amounts are available only at microblock that might have multiple channel transactions in a way that could lead to imprecision if we put in these transactions. It was added a parameter to `/channels/:channel` though to allow querying the channel state including the amounts and reserve at a specific micro block.
-  `ChannelSettleTx`: please use initiator_amount_final
