### ISSUE TITLE
Name swagger file consistent with Aeternity node

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#108]
The aeternity node's swagger file named `/api`, but the middleware's swagger file for some reason has path `/swagger/swagger.json`. Proposing to put it to the same place as the node's swagger file for consistency.

https://mainnet.aeternity.io/api
https://mainnet.aeternity.io/mdw/swagger/swagger.json

Also, the same naming using the compiler and the old middleware:
https://compiler.aepps.com/api
https://mainnet.aeternal.io/middleware/api

**Comment by thepiwo** [comment]
I agree, this should be adjusted

**Comment by thepiwo** [comment]
closing in favour of general swagger improvements issue
