### ISSUE TITLE
`/aex9/balances/account` returning incorrect data

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/ae_mdw#1087]
https://testnet.aeternity.io/mdw/aex9/balances/account/ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy
https://testnet.aeternity.io/mdw/v2/aex9/account-balances/ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy?limit=100
amount for this contract for example is different
ct_T6MWNrowGVC9dyTDksCBrCCSaeK3hzBMMY5hhMKwvwr8wJvM8

same on mainnet
https://mainnet.aeternity.io/mdw/aex9/balances/account/ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy
https://mainnet.aeternity.io/mdw/v2/aex9/account-balances/ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy?limit=100

ct_2qFg7M6MFdQioY3LQMUJh4b4awhK6rsEdi9pCf4cigkmFjQGkv

**Comment by jyeshe** [comment]
Fixed by #1094 (to take effect on previous balances after a resync)
