### ISSUE TITLE
Make names endpoint consistent named with Aeternity node

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#109]
Both middleware and aeternity node has an endpoint that returns name details by name, for example:

https://mainnet.aeternity.io/v2/names/davidyuk.chain
https://mainnet.aeternity.io/mdw/name/davidyuk.chain

The inconsistency is that "name" in plural form in the first case.  For me, the node's naming looks more traditional. Also, a similar case I have googled:

> GET http://www.example.com/customer/33245 or: GET http://www.example.com/customers/33245
There are good arguments on both sides, but the commonly-accepted practice is to always use plurals in node names to keep your API URIs consistent across all HTTP methods. The reasoning is based on the concept that customers are a collection within the service suite and the ID (e.g. 33245) refers to one of those customers in the collection.

https://www.restapitutorial.com/lessons/restfulresourcenaming.html

**Comment by skkw** [comment]
This is correct, it's oversight. 

Ideally, there would be a release which would fix these inconsistencies with synchronized progress so that other users of mdw don't get broken in the process but this is too much work for small benefit.
