### ISSUE TITLE
Fix order in the path of get_pointers_by_id endpoint

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#110]
https://mainnet.aeternity.io/mdw/name/pointers/davidyuk.chain

This endpoint returns a list of pointers of a name. From my perspective, these pointers are a part of the name record. The name record is returned by the `/name/<id>` endpoint, so it's pointers would be more reasonable to return by the `/name/<id>/pointers` path. In the Aeternity node, the similarly named paths are:
- /micro-blocks/hash/{hash}/header
- /micro-blocks/hash/{hash}/transactions
- /micro-blocks/hash/{hash}/transactions/count

**Comment by thepiwo** [comment]
@sborrazas whats the current state of this?

**Comment by sborrazas** [comment]
@thepiwo this was indeed fixed. Routes are not RESTful and nested correctly
