### ISSUE TITLE
Consistent naming of block fields in the transaction list

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#112]
https://mainnet.aeternity.io/mdw/txs/backward?account=ak_gvxNbZf5CuxYVfcUFoKAP4geZatWaC2Yy4jpx5vZoCKank4Gc&limit=1&page=1
```json
{
  "data": [
    {
      "block_hash": "mh_2Kp3YBWccEBxXMMuLKMg9KBqogubsvtbBnGEcRTnQCGnxjyLTT",
      "block_height": 350978,
      "hash": "th_2AkNF7rZUQxZFoweZpQixgFbv6gbBMBPn2o8Jev5QLGTRDyHiR",
      "micro_index": 0,
      "micro_time": 1606798357657,
      "signatures": [
        "sg_HoQymPXH6TMgs8vNmp1G9xNjJkqi3vViqErasKTP2LpHgHXc8qqjGY8F1zqiJA8tpop8MKRLyxBLcmWkqZSVQ2pXsdU44"
      ],
      "tx": {
        "amount": 1000000000000000000,
        "fee": 16840000000000,
        "nonce": 135,
        "payload": "ba_Xfbg4g==",
        "recipient_id": "ak_gvxNbZf5CuxYVfcUFoKAP4geZatWaC2Yy4jpx5vZoCKank4Gc",
        "sender_id": "ak_gvxNbZf5CuxYVfcUFoKAP4geZatWaC2Yy4jpx5vZoCKank4Gc",
        "type": "SpendTx",
        "version": 1
      },
      "tx_index": 18370234
    }
  ],
  "next": "txs/gen/350980-0?account=ak_gvxNbZf5CuxYVfcUFoKAP4geZatWaC2Yy4jpx5vZoCKank4Gc&limit=1&page=2"
}
```

As I understand, `micro_time` related to the micro block with a hash mentioned in `block_hash`. Would be nice to name it better, like `block_time` (to be more consistent) or even `micro_block_time` (to be more precise).

Also, `block_hash`, `block_height`, and `micro_time` seems to be related to the same entity, proposing to combine them into:
```json
"micro_block": {
  "hash": "mh_2Kp3YBWccEBxXMMuLKMg9KBqogubsvtbBnGEcRTnQCGnxjyLTT",
  "height": 350978,
  "time": 1606798357657,
}
```

The fields `block_hash`, `block_height`, `micro_index`, `micro_time` are they documented in the readme? Seems that doesn't because I can find their mentions only in examples.

**Comment by skkw** [comment]
I agree that these changes make sense, however fixing it now means creating more work for other teams which already integrate with current format.

**Comment by marc0olo** [comment]
agree that it's currently not worth the work. in future we should also cover such changes in a changelog.

@skkw can we put a respective label here and keep it open instead of closing it?
