### ISSUE TITLE
mainnet Websocket subscription Bug

### ISSUE THREAD

**Issue by Lfh2msn** [aeternity/ae_mdw#1122]
@thepiwo 
wss://mainnet.aeternity.io/mdw/v2/websocket
Subscribing to an account in the official mdw, or Transactions, is problematic. I initiate a normal transfer on the chain, mdw ws does not inform me.

Sometimes I can get a tx from the monitoring system, but I never receive my designated account or TX hash.

WeTrue has been using websocket heavily for a long time, and the problem occurred during a recent mdw upgrade.

ak_dMyzpooJ4oGnBVX35SCvHspJrq55HAAupCwPQTDZmRDT5SSSW
This is the WeTrue receiving account, and you can try to subscribe and initiate another transfer.

**Comment by thepiwo** [comment]
@sborrazas and @jyeshe are looking into it, there has been some problems with the deployment that we are fixing currently

**Comment by jyeshe** [comment]
@Lfh2msn the delivery of the transactions was normalized on mainnet and testnet. There might be some jitter though. If you run on premise, the recommended way, the fix is available on the latest published [image](https://hub.docker.com/r/aeternity/ae_mdw/tags).
