### ISSUE TITLE
sort names by activation to show recently claimed names

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#115]
**Actual**
Currently we can sort active names by `name` or `expiration`.

**Desired**
We also need to be able to sort by `activation` so that we can show the recently claimed names.

**Comment by thepiwo** [comment]
@marc0olo can you check again and update/close this issue?

**Comment by marc0olo** [comment]
@thepiwo I don't think this is possible right now:

```
{"error":"invalid query: by=activation"}
```

the usecase here is to display the recently claimed names
