### ISSUE TITLE
search for names

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#116]
**Past implementation**
We were able to perform a search for names.

**Current state**
We can only query by exact name using `/name/:id`
- btw. I need to mention that I personally would expect `/names` instead of `name` here

**Request**
It would be great for us to be able to search for names, e.g. by adding a query param `/names?query=marc` or `/names?search=marc`

**Comment by marc0olo** [comment]
on Superhero somebody asked for that feature in aenalyitcs:
- https://superhero.com/tip/38_v3/comment/1462

**Comment by thepiwo** [comment]
@marc0olo can you check again and update/close this issue?

**Comment by marc0olo** [comment]
searching is now possible :)

https://github.com/aeternity/ae_mdw#searching-names
