### ISSUE TITLE
Full name history endpoint

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1202]
Hey folks!

At aeScan we have been asked to implement a more detailed name activities (events) history, since relying on the name-related transactions only might be misleading for the AENS users. Unfortunately, there are some activities that don't have any associated transactions and happen implicitly in the blockchain. Here is what I mean by that:
let's say that a name has the following transaction history:

* NamePreclaimTx (2 days ago)
* NameClaimTx (2 days ago)

this can mean that:
a) somebody activated the name long enough that it didn't need any auction
b) somebody initialized an auction that had only 1 bid and already ended - in such case the name has been activated a day ago, when the auction ended
c) somebody initialized an auction that is still ongoing

To find out the name status at a given point of the name's history we would need to fetch the full history name and then calculate all the states based on protocol rules. It's not very optimal, so perhaps we could somehow obtain a more human-friendly history from the middleware instead of doing all the calculations on the front end?

Below I attach a table that contains all the activities we came up with. Perhaps there are some edge cases that are missing (e.g. some kind of transaction rejection). If there are some mistakes, please point them out

![image](https://user-images.githubusercontent.com/46789227/221193677-f723d7fd-b34b-4756-b80b-0e589ef93706.png)
![image](https://user-images.githubusercontent.com/46789227/221193699-26d35ab2-a841-4800-aa2a-de0449faf3a4.png)

**Comment by michele-franchi** [comment]
@sborrazas @jyeshe is this endpoint planned?

**Comment by jyeshe** [comment]
> @sborrazas @jyeshe is this endpoint planned?

I can take it before the sync feed.

**Comment by janmichek** [comment]
Hey there, regarding this implementation, I have some questions about to initial description.


1) How can I distinguish between Auction Initialized, Auction Ended, and Activated?

I cannot determine if it's a last bid or first bid as the response is paginated.



2) How can I distinguish Expired - I can somehow identify this one on FE, but still the response is paginated


3) AENS commitment initialized - according to description there should be this this displayed, but no Preclaim event is in the response. Should I create followup for this?
