### ISSUE TITLE
Invalid account transactions count

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1206]
Hey, I think that the transactions count endpoint returns a bigger count than the available transactions. e.g.

https://mainnet.aeternity.io/mdw/v2/txs?direction=backward&limit=10&account=ak_2epACQAj2w8EBX4AVodp3c4NE5N4HVMRLW7KvsA2ncbRV4QNbT

returns 6 records in the response
![image](https://user-images.githubusercontent.com/46789227/221570253-2a6452b4-936e-4197-816f-1ef3505837cb.png)

while 

https://mainnet.aeternity.io/mdw/v2/txs/count?id=ak_2epACQAj2w8EBX4AVodp3c4NE5N4HVMRLW7KvsA2ncbRV4QNbT
returns 7
![image](https://user-images.githubusercontent.com/46789227/221570341-a8d76ee5-2cc4-48bc-982a-13f9c0a8036b.png)

Another example:
https://mainnet.aeternity.io/mdw/v2/txs/count?id=ak_gZ55FLJoGEfF5gJ2xJU7j9uSH3fEjoTZq3ygQG8gYA4no6GFW&tx_type=ga_meta return 144
https://mainnet.aeternity.io/mdw/v2/txs?direction=backward&limit=10&account=ak_gZ55FLJoGEfF5gJ2xJU7j9uSH3fEjoTZq3ygQG8gYA4no6GFW&type=ga_meta
returns empty data

It looks like the issue is occurring in some specific scenarios because many of the accounts return correct results in both endpoints.

**Comment by sborrazas** [comment]
> Hey, I think that the transactions count endpoint returns a bigger count than the available transactions. e.g.
> 
> https://mainnet.aeternity.io/mdw/v2/txs?direction=backward&limit=10&account=ak_2epACQAj2w8EBX4AVodp3c4NE5N4HVMRLW7KvsA2ncbRV4QNbT
> 
> returns 6 records in the response ![image](https://user-images.githubusercontent.com/46789227/221570253-2a6452b4-936e-4197-816f-1ef3505837cb.png)
> 
> while
> 
> https://mainnet.aeternity.io/mdw/v2/txs/count?id=ak_2epACQAj2w8EBX4AVodp3c4NE5N4HVMRLW7KvsA2ncbRV4QNbT returns 7 ![image](https://user-images.githubusercontent.com/46789227/221570341-a8d76ee5-2cc4-48bc-982a-13f9c0a8036b.png)
> 
> Another example: https://mainnet.aeternity.io/mdw/v2/txs/count?id=ak_gZ55FLJoGEfF5gJ2xJU7j9uSH3fEjoTZq3ygQG8gYA4no6GFW&tx_type=ga_meta return 144 https://mainnet.aeternity.io/mdw/v2/txs?direction=backward&limit=10&account=ak_gZ55FLJoGEfF5gJ2xJU7j9uSH3fEjoTZq3ygQG8gYA4no6GFW&type=ga_meta returns empty data
> 
> It looks like the issue is occurring in some specific scenarios because many of the accounts return correct results in both endpoints.

@lukeromanowicz as for the first case, since it appears in the same transaction twice (th_2Pirj6ENnCimXEdgs4EJzQumLYbXa5vUeCfyeNQbEVgugDJAHv) it's counted twice. I'll try to work out a solution for this

For the second case, I'm no longer seeing any results, I'm not sure what could have changed or if there's anything that might have been fixed already.

**Comment by sborrazas** [comment]
Done
