### ISSUE TITLE
cannot run docker image?!

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#121]
Hi @Artur64,

it seems like I am not able to get the docker image running. Neither by running it directly, nor by running the docker-compose included in the repository.

I always get the following error:
```
standard_init_linux.go:219: exec user process caused: no such file or directory
```

Besides that I am wondering what's included in the image of the middleware. Does it contain the **node**, the **middleware** and the **frontend** of the middleware? Or "just" the node and the middleware?

I am wondering how to run an image of the middleware that connects to an already running node. Is that possible with the current docker setup?

**Comment by marc0olo** [comment]
ok nevermind about the error. it was due to the windows lineendings in the  `entrypoints.sh`. after changing it works as expected.

following questions remain:
- is the frontend being built in the same image and is it also being started with the entrypoint script?
- is it possible to configure the image to run against an outside (already running) node?

**Comment by Artur64** [comment]
Hi @marc0olo ,
So, just to give you overall understanding of current docker setup - it runs our own middleware backend which first [compiles](https://github.com/aeternity/ae_mdw/blob/master/Dockerfile#L48) backend, then compiles frontend while building image and then just [runs phoenix](https://github.com/aeternity/ae_mdw/blob/master/docker/entrypoint.sh#L3), which then [serves compiled js files](https://github.com/aeternity/ae_mdw/blob/master/lib/ae_mdw_web/endpoint.ex#L16) **separately** from backend.

So in the other words - MDW = backend(Current elixir-codebase + reused erlang aenode codebase) + compiled js frontend files (frontend). Thats why docker while building [downloads aeternity release](https://github.com/aeternity/ae_mdw/blob/master/Dockerfile#L20-L22), it depends on aeternity erlang modules [for instance](https://github.com/aeternity/ae_mdw/blob/master/lib/ae_mdw/application.ex#L56-L61) which are being reused. 

Regarding "possibility to configure mdw to work with other **node**" - first we must define what we call a "node" - if we define it as `aeternity` blockchain node - then the answer is **no** and I don't think that this can be done, as middleware project is **not** an `aeternity` node, it is a whole separate project now, which just reuses some codebase from erlang codebase for its own needs, for instance - structures and serializations, which are needed for us on protocol level. @skkw  , please, correct me if I am wrong here, or please, give better explanation in this regard. 


Serving js compiled files statically means that the frontend which is being run is still not configured to "work with/read data from" the node it is deployed - it is basically [old frontend](https://github.com/aeternity/aeternal/tree/develop/frontend) **without** any adjustments in regards of the "source" of the information it shows, as there became a lot of differences between structures/endpoints and stuff like that.

We are aware of this and there is already a task which requires some adjustment but in JS codebase frontend-side, but currently it is left as it was - it is reading/working and showing information from old middleware node(rust one).

**Comment by marc0olo** [comment]
Hi @Artur64,

thanks for giving me that short briefing. I understand that the middleware can be used as a plugin to the aeternity node. But from my interpretation the current docker image runs the aeternity node including the middleware as plugin, right?

I personally don't need a frontend so from my perspective the frontend could be dropped. Although I am wondering on what port this is served when it is also started by executing the `entrypoint.sh`.

Let's say I already have a running node which is in sync with the current block height and running in a docker container. How can I "install" the middleware plugin then? Or is it required that the middleware is running in the same image as the node itself? I know there are dependencies in regards to functionality. Just wondering whether it can be achieved that node and middleware run in separate containers.

From my view it would be perfect to have 3 images if I want to run the whole stack:
- aeternity node
- middleware
- frontend

Probably I am still missinterpreting. But when running the docker-compose I am quite sure that also a node is being started.

**Comment by Artur64** [comment]
Hey @marc0olo , if you want you can just start middleware image with the **database** you already have(which is produced by `aeternity` node) - here is [a link](https://github.com/aeternity/ae_mdw#docker-configuration) in documentation which mentions this possibility. 

Middleware starts some components of aeternity node inside, that's why it depends on [aeternity node's directory to be set correctly](https://github.com/aeternity/ae_mdw#setup) **NODEROOT** to be set correctly , if someone wants to start the mdw project by bare-building and running it.

**Comment by marc0olo** [comment]
Hi @Artur64, I am not sure whether we are talking about the same thing. I assume that the middleware needs the node dependency on compile time and I try to be more specific in my question:
- can I create a docker image of the middleware that only uses the node for compilation (e.g. by using multi-stage build via `AS builder`) and doesn't include the node in the image?
   - I am asking because I want to configure the **NODE_ROOT** so that it points to a volume which is also used by the node which itself is running in another container

In fact my requirement (if possible) is that I can run the middleware and the node in separate containers. From my perspective the current Dockerimage doesn't provide that. I guess I need to play around and test how I can achieve that. My guess is that I need the aeternity node for compilation of the middleware and then I should be able to run it without node-dependency in a separate container. Could this work if I run and configure the compiled and node-independent middleware image to point to **NODE_ROOT** in a shared volume of **node** and **middleware** which both run in independent containers?

The current Dockerimage runs both, the node **and** the middleware, right? Or am I wrong with this assumption?

Sorry for asking again, but I think we currently do not share the same perspective on that topic. Or I just don't understand how exactly the middleware depends on the node.

**Comment by marc0olo** [comment]
@Artur64 ok I had a chat with piwo and from my understanding it is not possible to run the middleware and the aeternity node in 2 different containers. so it always has to be packed in 1 image.

you can close the ticket if this is right. sorry for the trouble! :D

**Comment by marc0olo** [comment]
@Artur64 @skkw ok I got it working now with my own docker-compose setup. the `aeternity.yaml` and the keys folder need to be placed in `/home/aeternity/node/local/rel/aeternity`. unfortunately the middleware can only be started when the node is running with `ae_uat` or  `ae_mainnet` which means I cannot configure the fork heights.

I already opened an issue for that => #122

**Comment by thepiwo** [comment]
@marc0olo can you check again?

**Comment by marc0olo** [comment]
I think generally this can be closed as I got it working. I created this repository which includes a github action to build images for the middleware: https://github.com/kryptokrauts/ae-image-builder

but I think there should be a standardized way how to build production ready images for plugins like `ae_mdw` making use of https://github.com/aeternity/ae_plugin.

ideally we would be able to combine multiple "plugins" in a single docker-image including the node (which is obviously required for the plugins to run)

**Comment by thepiwo** [comment]
the Dockerfile included in this repository also works fine for me

**Comment by marc0olo** [comment]
yes it is basically based on the Dockerfile. I just think there are things that can be improved:
- image size (node image uses ~145mb whereas the mdw including the node requires ~555mb)
- file structure (I would appreciate if it reflects a similar folder structure as the node image at least for the node related stuff)
- specify a specific user and that the containers of the image aren't running with root

should I summarize this stuff in a new issue?

**Comment by thepiwo** [comment]
lets make a new issue for this, as it's not a bug any more
