### ISSUE TITLE
hardfork detection based on node configuration in aeternity.yaml

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#122]
currently the middleware only supports the [default networks](https://github.com/aeternity/aeternity/blob/master/apps/aecore/src/aec_hard_forks.erl#L94) for hardfork detection.

it would be good if the middleware could detect the network and extract the hardfork height(s) based on the configuration in the `aeternity.yaml`.

cc: @skkw

**Comment by marc0olo** [comment]
@skkw it seems like I am also able to use the networks for local testing:
- `local_roma_testnet`
- `local_minerva_testnet`
- `local_fortuna_testnet`
- `local_iris_testnet`

unfortunately an explicit network for **Lima** is missing. would it be possible to add this in the upcoming release 5.6 of the node? then this would be sufficient for me to perform a local integration testing with the middleware.

**Comment by velzevur** [comment]
@marc0olo the upcoming release 5.6 will have the missing `local_lima_testnet`. This is orthogonal to this issue regarding the MDW being hard fork aware.

**Comment by skkw** [comment]
Sorted out at the AE Node level.
