### ISSUE TITLE
Wrong transaction count of specific type when fetching by account id

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1236]
When fetching tx count by account id and specific type I am getting as a result count of all transactions of that type instead of count of all transactions of that type related to that account:
e.g.
https://mainnet.aeternity.io/mdw/v2/txs/count?id=ak_276FaXv9UX1kEgQMar4dQyEYneTD5MiyZfRpJbuU5UyYDFvRdq&tx_type=contract_call
returns 591159

https://mainnet.aeternity.io/mdw/v2/txs/count?id=ak_276FaXv9UX1kEgQMar4dQyEYneTD5MiyZfRpJbuU5UyYDFvRdq
returns 355

**Comment by jyeshe** [comment]
It should return an error on the first case because it was unsupported. 
It will filter by both params. 
Thanks @lukeromanowicz

**Comment by janmichek** [comment]
Still does not seem to be solved 


https://github.com/aeternity/ae_mdw/assets/15363559/8ca25af6-3839-4262-b7e4-cf3497468342

**Comment by jyeshe** [comment]
@janmichek there is a lack of proper validation on `/count`. 

The actual endpoint is `/count/:id`:
https://mainnet.aeternity.io/mdw/v2/txs/count/ak_276FaXv9UX1kEgQMar4dQyEYneTD5MiyZfRpJbuU5UyYDFvRdq
Which can be filtered by:
https://mainnet.aeternity.io/mdw/v2/txs/count/ak_276FaXv9UX1kEgQMar4dQyEYneTD5MiyZfRpJbuU5UyYDFvRdq?type=contract_call

The `/count` will be adapted to route to `/count/:id`

**Comment by janmichek** [comment]
> @janmichek there is a lack of proper validation on `/count`.
> 
> The actual endpoint is `/count/:id`: https://mainnet.aeternity.io/mdw/v2/txs/count/ak_276FaXv9UX1kEgQMar4dQyEYneTD5MiyZfRpJbuU5UyYDFvRdq Which can be filtered by type: https://mainnet.aeternity.io/mdw/v2/txs/count/ak_276FaXv9UX1kEgQMar4dQyEYneTD5MiyZfRpJbuU5UyYDFvRdq?type=contract_call
> 
> The `/count` will be adapted to route to `/count/:id`

Thanks for explanation .) I made it working in aescan
