### ISSUE TITLE
Circulating supply looks incorrect

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/ae_mdw#1244]
The circulating supply returned from the [totalstats](https://mainnet.aeternity.io/mdw/v2/totalstats) is now ~379M (total_token_supply) and it looks incorrect.

The circulating supply at this time it should be ~412M:
https://www.coingecko.com/en/coins/aeternity
https://aeknow.org/miner/inflation

**Comment by janmichek** [comment]
https://www.aeknow.org/api/totalcoins
