### ISSUE TITLE
Outdated Token docs

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1247]
![image](https://user-images.githubusercontent.com/15363559/228790802-8b5506e8-6cb9-4dc3-bcbf-b508c08084b2.png)
VS
![image](https://user-images.githubusercontent.com/15363559/228790827-b00d1758-d4bf-4bc4-aedf-f717823c376b.png)

https://github.com/aeternity/ae_mdw#aex9-tokens
VS
https://mainnet.aeternity.io/mdw/aex9/by_name

**Comment by janmichek** [comment]
Also all aex9 section does not refer to `v2`. Please fix it

**Comment by jyeshe** [comment]
> Also all aex9 section does not refer to `v2`. Please fix it

You can find `v2` here: https://mainnet.aeternity.io/mdw/swagger/swagger_v2.yaml
