### ISSUE TITLE
active auction is not being listed

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#125]
I am currently running the middleware locally for integration testing using the network id `local_iris_network`. it seems like active auctions are not being displayed.

what can be the reason? the `/status` endpoint tells me that the middleware is in sync

is this a bug?

**Comment by marc0olo** [comment]
it seems like the middleware doesn't detect the auction correctly and instead sets the name immediately to `"active":true` and `"status":name`

**Comment by skkw** [comment]
This shouldn't happen anymore - was a consequence of auction time set to 0, so that all auctioned names were claimed immediately.
