### ISSUE TITLE
Filtering oracles by state always returns the same result

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1272]
If I am testing the endpoint `/oracles` correctly, it looks like `state` filter is broken and always returns the same result.

Example:
https://testnet.aeternity.io/mdw/v2/oracles?limit=10&state=active
https://testnet.aeternity.io/mdw/v2/oracles?limit=10&state=inactive

**Comment by jyeshe** [comment]
closed by #1491
