### ISSUE TITLE
Count inactive names and oracles once per object

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#1278]
`/v2/totalstats` inherited from `v1` the inactive names and oracles counters that are incremented per expiration. However both names and oracles might expire multiple times (oracle considering the pubkey, not the oracle id). 

`/v2/totalstats` needs to be improved to consider only new expirations and decrement the inactive counter when the object is reactivated.

**Comment by lukeromanowicz** [comment]
Looking at the /v2/oracles endpoint it currently returns only 58 oracles, while the totalstats endpoint reports:

active_oracles:32
inactive_oracles: 340

I'm afraid one of the endpoint is working incorrectly

**Comment by jyeshe** [comment]
> Looking at the /v2/oracles endpoint it currently returns only 58 oracles, while the totalstats endpoint reports:
> 
> active_oracles:32
> inactive_oracles: 340
> 
> I'm afraid either one of the endpoints is working incorrectly or I misuse/misunderstand how they work and what they return

We need a full resync to see the correct result. Thanks for double checking Luke.

**Comment by jyeshe** [comment]
@lukeromanowicz cc @michele-franchi the Mdw is updated with a counting that depends on actual keys (not on operations) so it should be fine by now (for latest generations, after 824600, for previous ones it's needed to wait for a full resync).
