### ISSUE TITLE
Docker image crashes with unclear exception if `data/mdw.db` is not mounted

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1281]
Steps to reproduce:
1. clone this repo
1. remove `- ${PWD}/data/mdw.db:/home/aeternity/node/local/rel/aeternity/data/mdw.db` line in `docker-compose.yml`
1. run `docker-compose up`

It would fail with
```
...
ae_mdw-ae_mdw-1  | 10:17:53.548 [info] Application telemetry_poller started on node aeternity@localhost
ae_mdw-ae_mdw-1  | 10:17:53.550 [info] Application tesla started on node aeternity@localhost
ae_mdw-ae_mdw-1  | 10:17:53.564 [info] Application websockex started on node aeternity@localhost
ae_mdw-ae_mdw-1  | 10:17:55.148 [error] CRASH REPORT Process <0.562.0> with 0 neighbours exited with reason: no match of right hand value error in 'Elixir.AeMdw.Application':start/2 line 39 in application_master:init/4 line 138
ae_mdw-ae_mdw-1  | {"Kernel pid terminated",application_controller,"{application_start_failure,ae_mdw,{bad_return,{{'Elixir.AeMdw.Application',start,[normal,[]]},{'EXIT',{{badmatch,error},[{'Elixir.AeMdw.Application',start,2,[{file,\"lib/ae_mdw/application.ex\"},{line,39}]},{application_master,start_supervisor,3,[{file,\"application_master.erl\"},{line,331}]},{application_master,start_the_app,5,[{file,\"application_master.erl\"},{line,313}]},{application_master,start_it_new,7,[{file,\"application_master.erl\"},{line,299}]}]}}}}}"}
ae_mdw-ae_mdw-1  | Kernel pid terminated (application_controller) ({application_start_failure,ae_mdw,{bad_return,{{'Elixir.AeMdw.Application',start,[normal,[]]},{'EXIT',{{badmatch,error},[{'Elixir.AeMdw.Application',sta
ae_mdw-ae_mdw-1  | 
ae_mdw-ae_mdw-1  | Crash dump is being written to: erl_crash.dump...done
ae_mdw-ae_mdw-1 exited with code 1
```

It fails the same in 1.45.0, 1.44.0, 1.43.0

**Comment by jyeshe** [comment]
It's logged on log/info.log:
```
2023-05-03 08:47:26.527 [error] Failed to open database! path=/home/aeternity/node/local/rel/aeternity/data/mdw.db, reason={:db_open, 'IO error: while open a file for lock: /home/aeternity/node/local/rel/aeternity/data/mdw.db/LOCK: Permission denied'}
```

In this case for permission but also if cannot create when missing/not mounted.

**Comment by davidyuk** [comment]
Can it be not necessary to mount this value? I'm going to run mdw in e2e tests, so a new database can be created each time.

What is the difference between messages in log/info.log and ones send to stdout?

**Comment by jyeshe** [comment]
> Can it be not necessary to mount this value? I'm going to run mdw in e2e tests, so a new database can be created each time.
> 
> What is the difference between messages in log/info.log and ones send to stdout?

Whenever the user runs the mdw there is an option to delete the content of `mdw.db` mapped directory. Along with the command of spawning the mdw, could you add one to recreate the `mdw.db`? If there is any caveat, we can make the mapping optional though.

The `log/info.log` contains the messages from error handling.

**Comment by davidyuk** [comment]
> If there is any caveat, we can make the mapping optional though.

This would be the best, I'm using docker-composes to run the local test environment and I would like to keep it as simple as possible.

**Comment by davidyuk** [comment]
> The log/info.log contains the messages from error handling

I think that message is so important that should be printed to stdout.
