### ISSUE TITLE
ae_mdw releases / tags

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#129]
@skkw when will you start publishing releases? I want to create a setup that builds the aeternity image (node + middleware) by providing respective release numbers.

currently I need to rely on the master branch of the middleware which I want to avoid if possible

**Comment by skkw** [comment]
We now have the first release - 1.0.0. and plan to stick with producing releases anytime it makes sense.

**Comment by marc0olo** [comment]
thanks! 👍  would also be great if you can provide release notes for the future releases
