### ISSUE TITLE
Endpoint `v2/names` with `owned_by` param returning 500 for some accounts

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/ae_mdw#1293]
This endpoint `v2/names` with query `owned_by` returning 500 error on particuary account, not for every

https://mainnet.aeternity.io/mdw/v2/names?owned_by=ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy

`Internal Server Error`

for this account the responce is correct
https://mainnet.aeternity.io/mdw/v2/names?owned_by=ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ

**Comment by sborrazas** [comment]
This was now fixed
