### ISSUE TITLE
Oracle query and associated response

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/ae_mdw#1295]
It would be nice to have a way to get the associated response of a query, if available, and ideally in a single endpoint.

With the following data:
- Query Tx
- Queried At
- Respond Tx
- Respond At
- Status: Response pending, Response available, Response expired, Query timed out (should be calculated based on the TTL)

I see two cases:

1. Query sent, no response sent
- Query id
- Query fee
- Query TTL

2. The query has a response
- Query id
- Query fee
- Query
- Response
- Response TTL

I'm not suggesting a structure, just the minimum ideal information that could be returned from the paginated endpoint.

**Comment by sborrazas** [comment]
This is now done and deployed to prod

**Comment by janmichek** [comment]
Seems like there are still some values missing to achieve what we want
https://user-images.githubusercontent.com/15363559/236007821-6a18fee4-65f4-4cb3-89a8-8553c19935de.png

Namely:
- Query block height
- Response block height 
- Status

**Comment by sborrazas** [comment]
> Seems like there are still some values missing to achieve what we want https://user-images.githubusercontent.com/15363559/236007821-6a18fee4-65f4-4cb3-89a8-8553c19935de.png
> 
> Namely:
> 
> * Query block height
> * Response block height
> * Status

@janmichek height is now part of queries/responses. It is also included on the oracle detail for which `height < expire_height ? active : inactive`
