### ISSUE TITLE
Implement equivalent of node's `int-as-string` option

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1301]
This is how it works in the node
https://mainnet.aeternity.io/v3/status
https://mainnet.aeternity.io/v3/status?int-as-string

The reasoning is to improve developer experience in case JSON parser doesn't support big integers and/or to simplify integration with other tools.

For example, in JS SDK I was using a custom parser that supports big integers, but I wanted to use [autorest](https://github.com/Azure/autorest), and I didn't find a way to integrate custom parser there, so asked the core team to implement something, and at the end it uses `int-as-string`. I'm planning to use Middleware the same way, so asking you to implement the same solution as node did (for consistency) or do something in the same fashion (for example, convert only ae amounts to strings).

Also, would be nice to have this option in websocket interface.

**Comment by thepiwo** [comment]
@davidyuk is this still current, I think we would also need this in another project @sborrazas @jyeshe

**Comment by sborrazas** [comment]
@thepiwo this is indeed current, and I think very useful after working with contracts a bit. I'll prioritize it and start working on it as soon as I can

**Comment by sborrazas** [comment]
Done
