### ISSUE TITLE
Aex9 tokens `by name` sorted differently in v1 and v2

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/ae_mdw#1333]
https://mainnet.aeternity.io/mdw/v2/aex9?by=name&limit=100
```
[
    {
       "name":"yy"
    },
    {
       "name":"xx"
    },
    {
       "name":"xok"
    },
    {
       "name":"wewe"
    },
    {
       "name":"valentina"
    },
    {
       "name":"tet"
    },
    {
       "name":"testtoken"
    },
    {
       "name":"testnetAE"
    }
 ]
 ```
https://mainnet.aeternity.io/mdw/aex9/by_name
```
[
    {
       "name":"911058"
    },
    {
       "name":"9GAG"
    },
    {
       "name":"AAA"
    },
    {
       "name":"AAA"
    },
    {
       "name":"AAA"
    },
    {
       "name":"AAA"
    },
    {
       "name":"AAA"
    },
    {
       "name":"AAA"
    },
    {
       "name":"AAA"
    },
    {
       "name":"AAA"
    }
 ]
 ```

**Comment by jyeshe** [comment]
Hey @CedrikNikita we had discussed about name sorting and it was decided that every v2 endpoint has descending sorting by default, not only for numbers but also for names as well. Please use the [direction](https://github.com/aeternity/ae_mdw/blob/775b66314dfa6957f47048bbbd585597bacbf73a/docs/swagger_v2/aexn.spec.yaml#L648) parameter. 
https://mainnet.aeternity.io/mdw/v2/aex9?by=name&limit=100&direction=forward
It's available for all paginated endpoints.
