### ISSUE TITLE
Missed `required` in Activity, PaginatedResponse, /accounts/{id}/activities response

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1361]
Activity's `required` I would set to `['block_hash', 'height', 'payload', 'type']`.

In PaginatedResponse, `required` should be `['next', 'prev']`, also set `nullable: true` for properties `next`, `prev`.

In `$.paths./accounts/{id}/activities.get.responses.200.content.application/json.schema.allOf[0]` set `required` to `data`.

Probably `required` is missed in other fields, without it, autorest marks properties as optional that required to add an additional check/assertion while accessing them.

**Comment by sborrazas** [comment]
This has been fixed and can be accessed in https://mainnet.aeternity.io/mdw/v2/api
