### ISSUE TITLE
`type: object` is missed in some components.schemas

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1363]
```
        'Activity', 'Aex9TransferEvent', 'Auction', 'ContractCall', 'ContractLog', 'DeltaStat',
        'InternalContractCallEvent', 'InternalTransferEvent', 'Name', 'NameClaim',
        'NameClaimEvent', 'NameTransfer', 'NameUpdate', 'PaginatedResponse', 'Tx',
```
the above schemas have `properties` field, but don't have corresponding `type: object`

> The schema 'Activity' with an undefined type and declared properties is a bit ambiguous.
      This has been auto-corrected to 'type:object'

**Comment by sborrazas** [comment]
This has been fixed and can be accessed in https://mainnet.aeternity.io/mdw/v2/api
