### ISSUE TITLE
`type: string` missed near `enum`

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1364]
$.components.schemas.Auction.properties.info.properties.status

> The enum schema 'Auction-info-status' with an undefined type and enum values is ambiguous. This has been auto-corrected to 'type:string'
      
$.components.schemas.Transfer.properties.kind

> The enum schema 'Transfer-kind' with an undefined type and enum values is ambiguous. This has been auto-corrected to 'type:string'

$.paths./names/search.get.responses.200.content.application/json.schema.allOf[0].properties.data.items.allOf[1].properties.status

 >  The enum schema 'get-200-application-json-allOf-properties-items-1-status' with an undefined
      type and enum values is ambiguous. This has been auto-corrected to 'type:string'

$.paths./txs.get.parameters[0].schema.items
>  The enum schema 'get-0-itemsItem' with an undefined type and enum values is ambiguous.
      This has been auto-corrected to 'type:string'
      
https://swagger.io/docs/specification/data-models/enums/

**Comment by sborrazas** [comment]
This has been fixed and can be accessed in https://mainnet.aeternity.io/mdw/v2/api
