### ISSUE TITLE
Some name activities are missing micro_time

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1385]
Some name activities are missing micro_time in the event's payload e.g. InternalContractCallEvent. Perhaps there are more cases but that's the only one I spotted so far

![image](https://github.com/aeternity/ae_mdw/assets/46789227/3d713458-b912-466a-b8cb-ed3e7aec55ed)

**Comment by sborrazas** [comment]
@lukeromanowicz the payload depends on the event type. So the fact that there are SOME attributes on some given payload type does not mean they will be present on others.

That said, we can probably move `micro_time` outside the payload, which would be the time at which the `block_hash` happened.

**Comment by sborrazas** [comment]
@lukeromanowicz all activities should now have `block_time` at the outermost level
