### ISSUE TITLE
REST API delayed updates

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1389]
Up until a few weeks ago REST API used to send very recent updates - maximum delay of a few seconds from the new microblock mint by a node and that microblock showing up in REST API results.

Now there is a delay of 5-90 seconds and the updates come in batches of about 1-20 microblocks at a time 

### Reproduction steps
refresh https://mainnet.aeternity.io/mdw/v2/key-blocks/kh_2EmLzfRy2BaEfeQ2yB4TT8qYqAorF3CPT3F27UXki3KjUugqTj/micro-blocks?limit=30
every 5 seconds

### Expectation
every 1-2 refresh a new microblock appears in the results

### Current result
most of the time the response stays the same. 5-90 seconds the response gets update dby about 1-20 new microblocks that have been minted since the last "update"

**Comment by jyeshe** [comment]
@lukeromanowicz it's solved for most cases, except when last microblocks have multiple internal calls on contract calls. For these there is still a pending optimization. On the other hand, for last 100 microblocks it returns within less than 200ms (without stress tests). To be monitored with stats after this pending enhancement.  

command: 
```
$ hash=$(curl -s https://mainnet.aeternity.io/mdw/v2/key-blocks?limit=1 | jq 'first(.data[]).prev_key_hash' | tr -d '"'); 
time curl -s https://mainnet.aeternity.io/mdw/v2/key-blocks/$hash/micro-blocks?limit=100
```

for 
```
$ echo $hash
kh_2G14t3kbfLF3V96SfAVgej6KzrtJygUiuj52hKyzYjXUJquHae
```

output with last 100 microblocks: 
```
{"data":[{"micro_block_index":34,"transactions_count":8,"hash":"mh_2PhFwNQsp6zJJdAYDec6oJrU5U3Dkwgabdd5vGwW5SqRAkNxUs","height":805218,"pof_hash":"no_fraud","prev_hash":"mh_2mvF7JSgkMfs6Jqm41MYXxBMMmtDTinqCjb7hKJLoxhwjmfDC1","prev_key_hash":"kh_m4pXLdbkA3uGsf1YKtCqozRArVkgoRGaRw4qCV2J1Wjkpopc7","signature":"sg_YxNdSpd8sLABTwYJJDWPjusxsoA2GMK6JHxu993oxyU7zQgn63kHJdDbe4mgdKxFtJcs8fuhEtGGPrmGWvApkqS24VaqJ","state_hash":"bs_21ckGXSW9ZgXv3dsxeGjTovVeNq8SVow8MKXVEZCVYRCYs5BTj","time":1690294130233,"txs_hash":"bx_zZw3zKXQWJwJj3JGXFfLF1ssMHtEPmsk8KEhooBnymAcweGMg","version":5},
...
{"micro_block_index":418,"transactions_count":9,"hash":"mh_hk1HruhyjrhLCRYmVJ8FEt7gb31gqpXpNRmNfbiN4yLcmbuWW","height":805219,"pof_hash":"no_fraud","prev_hash":"mh_2V4yHLFPRaEJgVWEyZAsMpYdD6UWyQ3qQfycKHHgCL4KTsY2Ua","prev_key_hash":"kh_2G14t3kbfLF3V96SfAVgej6KzrtJygUiuj52hKyzYjXUJquHae","signature":"sg_VV2ptkQ14SKqTRV2fdyzYqVUxcZHbt5dRDWTmvQpNSLHWg1gogD8v9KDUeMvRTgHnVBnzAVCmR4f1UtT8iBt7duk29LKS","state_hash":"bs_JECHzdKPYZjxYQCPcySMZHuBtCT1zUbSWHvjEunJXDuq2QEe8","time":1690295403620,"txs_hash":"bx_2m7oJZ2jmbkeneczqvfDWiSmiAU78FJo1mXqdvn3Eavihm6XWP","version":5}],"next":"/v2/key-blocks/kh_2G14t3kbfLF3V96SfAVgej6KzrtJygUiuj52hKyzYjXUJquHae/micro-blocks?cursor=417&limit=100","prev":null}
real	0m0,147s
user	0m0,008s
sys	0m0,012s
```

**Comment by lukeromanowicz** [comment]
@jyeshe wonderful job guys, it's working much better now!
