### ISSUE TITLE
websocket idle timeout

### ISSUE THREAD

**Issue by kenodressel** [aeternity/ae_mdw#139]
Expected behavior:
- the client opens a websocket
- the client sends an subscribe command
- the client should receive updates as long as no close command is send

Actual behavior
- the client opens a websocket
- the client sends an subscribe command
- No event happens for 60 seconds
- The connection is closed by the middlware

**Comment by wj2016** [comment]
Hi @kenodressel , thanks for raising the issue.

[This configuration](https://github.com/aeternity/ae_mdw/blob/master/config/config.exs#L39) should keep all websocket connections open forever. This configuration was set last April, so it should be included on all major servers already. I did some testing on main and test mdw servers. They both work as expected.

I will just close this issue now, but if you still have the issue, please feel free to open it again.
