### ISSUE TITLE
What frontend is build for this middleware?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#140]
The one from the `frontend` folder or https://github.com/aeternity/mdw-frontend?

`frontend` folder looks outdated, can we remove it and use mdw-frontend instead? Maybe as a git submodule?

**Comment by marc0olo** [comment]
I am wondering why a frontend is included in this repository at all. For the build of our Dockerimage I am only compiling the backend part.

I'd like to see that separated. Might confuse people looking into the repository.

**Comment by mradkov** [comment]
https://github.com/aeternity/mdw-frontend

This is the one which is being updated to the latest changes of mdw.

**Comment by skkw** [comment]
Unfortunately our frontend preparations in the same named directory weren't picked upon. 
They are in place there, supporting vue/nuxt, just in case we would like to have a totally self contained middleware, running frontend without node, directly from elixir.

Makes sense to remove it now, though.

**Comment by thepiwo** [comment]
Yes I agree, we should remove it
