### ISSUE TITLE
tag AEX9 contracts as non complaint

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#1410]
Balances and holders might vary from actual contract state if the contract is not fully complaint to AEX9.

At least when it is indexed with invalid values, these contracts could be tagged as non complaint to avoid end user confusion and analyzing case by case manually.

Byte code static analysis is also possible as the middleware already has it deserialized and could look for the LOGN [instructions](https://github.com/aeternity/protocol/blob/master/contracts/fate.md)

**Comment by vatanasov** [comment]
Solved by https://github.com/aeternity/ae_mdw/pull/1799
