### ISSUE TITLE
Serve swagger file as JSON instead of YAML

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1416]
Before I asked to [add "/api" endpoint](https://github.com/aeternity/ae_mdw/issues/108) in consistency with the node and compiler. It has been done. The only issue that remains is the format of the swagger file. In node and compiler, it is plain JSON, but in middleware it is YAML. While there is no difference for most tools working with swagger files, YAML is not supported out-of-the-box in browsers. So serving "/api" as JSON would be more friendly for web developers, the same as it would be consistent with node and compiler. Switching from YAML to JSON is not a breaking change because YAML is a superset of JSON.

https://mainnet.aeternity.io/mdw/api vs https://mainnet.aeternity.io/api?oas3

**Comment by sborrazas** [comment]
@davidyuk you should now be able to use https://mainnet.aeternity.io/mdw/v2/api?format=json or the legacy https://mainnet.aeternity.io/mdw/swagger/swagger.json from V1

**Comment by davidyuk** [comment]
Do you need yaml served at https://mainnet.aeternity.io/mdw/v2/api in some case?

**Comment by sborrazas** [comment]
For backwards compatibility now we are not able to change it

**Comment by davidyuk** [comment]
Is there a place where JSON can't be used instead of YAML?

> The YAML 1.2 specification was published in 2009. Its primary focus was making YAML a strict superset of JSON.

https://yaml.org/spec/1.2.2/#12-yaml-history

**Comment by sborrazas** [comment]
It would still break those clients that are expecting a YAML under that path

**Comment by davidyuk** [comment]
yep, but every JSON is a valid YAML document, does somebody have a self-written yaml parser that not based on the yaml spec?

**Comment by sborrazas** [comment]
@davidyuk I wasn't really sure the standard covered entirely every json file, but you're right. I'll try updating it and if anyone complains we can revert it back

**Comment by davidyuk** [comment]
Thank you! Sorry if I'm being too scrupulous

**Comment by sborrazas** [comment]
Added and deployed
