### ISSUE TITLE
Add further fields to include approximate time

### ISSUE THREAD

**Issue by sborrazas** [aeternity/ae_mdw#1425]
The fields and endpoints are the following:

- `approximate_last_updated_time` in `channels/{stateChannelId}`
- `approximate_last_updated_time` in `channels` endpoint
- `approximate_activated_time` in `names` (with expand=true) endpoint
- `approximate_auction_end_time` in `names/auctions` endpoint
- `approximate_expiration_time` and `approximate_auction_end_time` in `names/{name}` endpoint
- `approximate_created_time` in `accounts/{nameHash}/activities` (for cases if `micro_time` is not available) endpoint
- `approximate_created_time`  in  `contracts/logs?contract_id={contractId}` endpoint
- `approximate_activated_time` in `oracles` endpoint
- `approximate_registered_time` in `oracles/{oracleId}` endpoint

refs #831

**Comment by janmichek** [comment]
In the state channel responses, I see the attribute name `lastUpdatedTime` so this is the exact time, not an approximate?

**Comment by sborrazas** [comment]
> In the state channel responses, I see the attribute name `lastUpdatedTime` so this is the exact time, not an approximate?

@janmichek that is correct

**Comment by janmichek** [comment]
Question for the oracles responses:

![image](https://github.com/aeternity/ae_mdw/assets/15363559/a16fcd1f-94db-4db9-a001-c44b792372ed)

So the `registerTime` is the time value of `activeFrom`?
What is the value of `register` for? Is it a keyblock value? How it can be registered in future?

**Comment by sborrazas** [comment]
@janmichek the value for `register` is the transaction index of the register, same with `extends`. We had to keep txis for backwards compatibility, but please use `tx_hash=true` for these endpoints, which will be the behavior of v3. e.g. https://mainnet.aeternity.io/mdw/v2/oracles/ok_2NRBaMsgSDjZRFw4dU82KCqLa5W7aQdbJAzaFprTpjEGLAzroV?tx_hash=true

**Comment by sborrazas** [comment]
@janmichek that's true, `approximate_auction_end` should be present there to indicate when the auction will terminate, as oppose to expire_time which indicates when the name will expire. I'll add it to names

**Comment by janmichek** [comment]
> approximate_activated_time in names (with expand=true) endpoint

It seems to be missing (or some other similarly named value) in response

https://mainnet.aeternity.io/mdw/v2/names?state=active&by=activation&direction=backward&limit=4&expand=true&by=activation

**Comment by janmichek** [comment]
ping

**Comment by sborrazas** [comment]
@janmichek I forgot to reference this issue on the PR, but this is already implemented on https://github.com/aeternity/ae_mdw/pull/1573 and will be available on the next deploy

**Comment by janmichek** [comment]
There still seems to be 2 walues missing from initial requirements

`approximate_expiration_time` in names/{name} endpoint
https://mainnet.aeternity.io/mdw/v2/names/paradigm.chain

`approximate_activated_time` in names (with expand=true) endpoint
https://mainnet.aeternity.io/mdw/v2/names?state=active&by=activation&direction=backward&limit=4&expand=true&by=activation

Can you add it please?

**Comment by janmichek** [comment]
Hello, there does not seem to be `approximate_activated_time` to https://mainnet.aeternity.io/mdw/v2/names?state=active&by=activation&direction=backward&limit=4&expand=true&by=activation endpoint. 

Also, I got one new minor request to add `approximate_activated_time` to ` names/{name} `


Can you process it please?

**Comment by sborrazas** [comment]
@janmichek these changes are part of v3, and present on a route like https://mainnet.aeternity.io/mdw/v3/names?state=active&by=activation&direction=backward&limit=4&expand=true&by=activation . 

I will now add the `/names/:name` route to v3 as well.

**Comment by janmichek** [comment]
Excellent, thanks for clarification and further addition

**Comment by sborrazas** [comment]
`/names/:name` added to v3

**Comment by sborrazas** [comment]
@janmichek can you indicate where the name fee appears in v2?

**Comment by janmichek** [comment]
> @janmichek can you indicate where the name fee appears in v2?

UPDATE:

1. I cannot switch to V3 of `/names/:name` because there are pointers missing
2. I cannot switch to V3 of ` https://mainnet.aeternity.io/mdw/v3/names?state=active&by=activation&direction=backward&limit=4&expand=true&by=activation` because there is a name_fee missing

**Comment by sborrazas** [comment]
@janmichek sorry, but I didn't see where the name fee is. can you indicate where the name fee appears in v2?

**Comment by janmichek** [comment]
> @janmichek sorry, but I didn't see where the name fee is. can you indicate where the name fee appears in v2?

https://mainnet.aeternity.io/mdw/v2/names?state=active&by=activation&direction=backward&limit=4&expand=true&by=activation

![image](https://github.com/aeternity/ae_mdw/assets/15363559/788429a8-b458-4ce3-ad2d-e0517598ee5b)

**Comment by sborrazas** [comment]
@janmichek it's part of the first claim, not the top name object. In v3, we no longer return nested lists of things, this is not proper API design. Would you rather include `name_fee` attribute on the name?

**Comment by janmichek** [comment]
I see. It does not have to be a nested value with the whole history of claims. This is the UI I want to preserve 
![image](https://github.com/aeternity/ae_mdw/assets/15363559/895b0255-1f9f-4462-9b82-79e195a0e921)

**Comment by sborrazas** [comment]
@janmichek cool, I'll update the name so that it includes this information, that way you won't have to rely on nested lists of claims, or any list of anything, including pointers

**Comment by sborrazas** [comment]
> Hello, I can see now that nameFee has been exposed, but I still miss the pointers Is it something that will be delivered?
> 
> Side question: You mention that a nested list is an antipattern for API, but for the name in auction, I cab see a nested object. Why it's like that? (I don't have specific preference, just curious )

Nested lists are part of the old legacy API which was not properly designed. V3 shouldn't contain any of these lists, auctions currently doesn't: https://mainnet.aeternity.io/mdw/v3/names/auctions

**Comment by janmichek** [comment]
> Hello, I can see now that nameFee has been exposed, but I still miss the pointers
> Is it something that will be delivered?

@sborrazas

**Comment by janmichek** [comment]
@yaboiishere @sborrazas

**Comment by sborrazas** [comment]
Pointers are already returned via the `/v3/names/:id/pointers` endpoint https://mainnet.aeternity.io/mdw/v3/names/unchain.chain/pointers. But for some reason it's not paginated, we will work on that next

**Comment by janmichek** [comment]
> Pointers are already returned via the `/v3/names/:id/pointers` endpoint https://mainnet.aeternity.io/mdw/v3/names/unchain.chain/pointers. But for some reason it's not paginated, we will work on that next

Should I daisy chain the call of  `/v3/names/:id/pointers` for every row in `v3/names` listing? The previous v2 solution was just fine.

**Comment by sborrazas** [comment]
Pointers is now part of the names object on v3. Closing
