### ISSUE TITLE
aex-9 token contract not recognized

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#1477]
just had some discussion with @thepiwo regarding this.

there seems to be a bug when an aex-9 token contract is deployed via contract factory.

this contract should be recognized as aex-9 token but it is not:
- https://testnet.aeternity.io/mdw/v2/aex9/ct_YdHhKgfAgvv7DMFRHNNM2pwLb3cMoZD5dj4YdbYgwiHv5EzAc

**Comment by jyeshe** [comment]
It's fixed, it was detecting only `Chain.create`.
