### ISSUE TITLE
get NFTs owned by a specific account for a specific contract/collection

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#1479]
I just saw some nft related PR and recently I wanted to fetch this info. I think it would be great being able to fetch this data.

maybe just extend following endpoint with a filter option for a contract/collection?

`GET /v2/aex141/owned-nfts/:account_id`

probably another endpoint would be better as the response format would most likely differ. in case of provided contract id we could just return a list of ids.

currently the response includes contract and owner for each nft:

```json
{
   "data":[
      {
         "contract_id":"ct_2cFUyFZfnCFXrUvW9e3i8sa3w8qU7YRoZDai4DEmSWyr4ty1jB",
         "owner_id":"ak_dwYGBWwLbuMTSmg8BL1STffp1Hnk4qziQYhSE36Y41vYFsyqS",
         "token_id":1
      }
   ],
   "next":null,
   "prev":null
}
```

**Comment by marc0olo** [comment]
in my case I have included an entrypoint in the contract that can return the owned nft ids of a user. but this is just a helper entrypoint that is not part of the standard interface

**Comment by jyeshe** [comment]
> I just saw some nft related PR and recently I wanted to fetch this info. I think it would be great being able to fetch this data.
> 
> maybe just extend following endpoint with a filter option for a contract/collection?
> 
> `GET /v2/aex141/owned-nfts/:account_id`
> 
> probably another endpoint would be better as the response format would most likely differ. in case of provided contract id we could just return a list of ids.
> 
> currently the response includes contract and owner for each nft:
> 
> ```json
> {
>    "data":[
>       {
>          "contract_id":"ct_2cFUyFZfnCFXrUvW9e3i8sa3w8qU7YRoZDai4DEmSWyr4ty1jB",
>          "owner_id":"ak_dwYGBWwLbuMTSmg8BL1STffp1Hnk4qziQYhSE36Y41vYFsyqS",
>          "token_id":1
>       }
>    ],
>    "next":null,
>    "prev":null
> }
> ```

for now implemented on v2 as a parameter, on v3 the best approach gonna be reviewed
