### ISSUE TITLE
Statistics endpoint definition for transaction types

### ISSUE THREAD

**Issue by sborrazas** [aeternity/ae_mdw#1492]
The following outlines the specifications for the statistics endpoint, designed to provide chartable data that can be seamlessly displayed in a chart.

These endpoints offer both filtering and pagination functionalities, enabling the efficient retrieval of results. With these features, users can easily access the specific data they need, streamlining the charting process and enhancing the overall user experience.

All endpoints support the following query params:

* `interval` - Specifies the interval between values. This can be `generation`, `daily`, `weekly` or `monthly`. Defaults to `daily`.
* `scope` - If given, scopes the results between the two dates. In the format of `1590883200000-1607817600000`. Defaults to 3 years back from the current date/generation. **TBD** according to desired server capacity.
* `direction` - `forward` or `backward` (default `backward`)

## Endpoints

The structure for all endpoints follow the same structure as any cursor-based paginated endpoint, which includes `prev`, `next` and `data`.
In this case, each data object would include the `start_time` in which that interval started and the `count` of objects resulting up until the next start time.

```
{
  "data": [
    {
      "start_time": 1690901323472,
      "count": 18
    },
    ...
  ]
  "prev": null,
  "next": "/statistics/txs?cursor=<next-cursor>"
}
```

## `/statistics/txs`

Displays the amount of transactions (total) or filtered transaction type on a given timeframe.

Additional query params:

* `tx_type` - If given, it will filter only the transactions of that type (e.g. `tx_type=contract_call`)

## `/statistics/aexn-transfers`

Displays amount of calls made to aexn contracts (both aex9 and ax141).

Additional query params:

* `type` - `type=aex9` or `type=aex141`.

**TODO**: Do we want to keep track of tranfers, or contract calls made to AExN contracts?

## `/statistics/blocks`

Displays amount of key-blocks (or micro-blocks) on the given timeframe, which allows to see the historial rate in which they were being added to the chain.

Additional query params:

* `type` - `type=key` or `type=micro`.

**Comment by michele-franchi** [comment]
Good analysis @sborrazas, I have some questions.

1) I see you mentioned pagination but how would it exactly work? For example if a frontend app wants to display a chart with the amount of transactions of the last 365 days it would mean it has to extract 365 records and if this is done with multiple HTTP requests it would probably takes a lot of time, compared to a single HTTP call.

2) Regarding /statistics/aexn-transfers if these are contract calls, wouldn't it make sense to name it something like /contract-calls and maybe add the option to filter aexn contracts? But I see your open note regarding transfers.
In my opinion it would be nice to have both, contract calls and token transfers

**Comment by sborrazas** [comment]
@michele-franchi here's my comments

> Good analysis @sborrazas, I have some questions.
> 
> 1. I see you mentioned pagination but how would it exactly work? For example if a frontend app wants to display a chart with the amount of transactions of the last 365 days it would mean it has to extract 365 records and if this is done with multiple HTTP requests it would probably takes a lot of time, compared to a single HTTP call.

The limit of results would be much higher than the rest of the endpoints. In most cases you will retrieve these results in a single page, but we need to have pagination to be able to cap results so we don't have issues in the future.

> 2. Regarding /statistics/aexn-transfers if these are contract calls, wouldn't it make sense to name it something like /contract-calls and maybe add the option to filter aexn contracts? But I see your open note regarding transfers.
>    In my opinion it would be nice to have both, contract calls and token transfers

We can have both `aexn-calls` and `aexn-transfers`, I would rather avoid the `txs` endpoint for it, since I'd like that endpoint to return data related to raw transactions and not the internal interpretation of contract calls

**Comment by sborrazas** [comment]
@michele-franchi you can already start to try out these endpoints on staging (yet to finish a full sync):

* https://staging.mdw.mainnet.aeternity.io/mdw/v3/statistics/transactions
* https://staging.mdw.mainnet.aeternity.io/mdw/v3/statistics/transactions?tx_type=contract_call
* https://staging.mdw.mainnet.aeternity.io/mdw/v3/statistics/blocks
* https://staging.mdw.mainnet.aeternity.io/mdw/v3/statistics/blocks?type=key

**Comment by sborrazas** [comment]
This is on prod already.
