### ISSUE TITLE
Exposing more Contract Call details in AEX-9- and AEX-141-related  ContractCallTxEvent

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1505]
Would it be possible to expose more contract call details in ContractCallTxEvent related to AEX-9 and AEX-141 such as Token Symbol, the collection name (in AEX-141), and the amount of tokens that the transaction refers to?

We want to show as much information as possible in account activities when a user interacts with known contracts.

**Comment by sborrazas** [comment]
@lukeromanowicz currently for aex9 we're returning the amount and all the other data that you can get from the regular balances endpoint (e.g. https://mainnet.aeternity.io/mdw/v2/accounts/ak_uTWegpfN6UjA4yz8X4ZVRi9xKEYeXHJDRZcRryTsRHAFoBpLa/activities?type=aexn and https://mainnet.aeternity.io/mdw/v2/aex9/ct_2F8BdAtpuiJjLiPkrdhFWgTrSpD7kZsVSw2apMRAeikUyoMrUJ/balances)

Same for aex141, where we display the `token_id`:
https://mainnet.aeternity.io/mdw/v2/aex141/ct_2w7MHbcyk5iM4yijZmjGcUF2DSZuVM1Mueppx5SSvPn5cgLJuZ/owners
and 
https://mainnet.aeternity.io/mdw/v2/accounts/ak_uTWegpfN6UjA4yz8X4ZVRi9xKEYeXHJDRZcRryTsRHAFoBpLa/activities?type=aexn

For both aex9 and 141 we can include the collection name (or symbol) for further information, I'll work on that. But I think everything else has been already accounted for

**Comment by lukeromanowicz** [comment]
@sborrazas yes, I confirm that some of the information we require is available when requesting other contract data from different endpoints. Unfortunately, it means that to show all of the basic information about an activity we need to perform multiple requests for each activity. Taking into consideration a page with 10 activities it means tens of requests for every page. I think that the additional traffic it generates is quite suboptimal for both aeScan and the middleware

**Comment by sborrazas** [comment]
@lukeromanowicz I understand that, but the URLs I sent were to show that what's currently being displayed on the activities endpoint is what the `/balances` for aex9 and `/owners` for aex141 endpoints provide. All the things that you mentioned with the exception of collection name/symbol are already included on the activities endpoint, am I missing anything?

**Comment by lukeromanowicz** [comment]
I understand the token_id property is the symbol of the token (didn't know that this is the meaning of that property). What's the property for the amount that a given transfer moved? Maybe my understanding of `*/balances` endpoint is wrong but I suppose it provides the information on the balance of an account taking into consideration all of the transfers, not one by one separately.

**Comment by sborrazas** [comment]
@lukeromanowicz `amount` when it appears under the `/balances` endpoint is indeed the total current amount. `amount` when it appears on a `Aex9TransferEvent` is indeed only the amount changed.

For the activitites filtering, you can filter exclusively aexn transactions on the activities endpoint using `?type=aexn` filter

**Comment by lukeromanowicz** [comment]
Well... we want to include also the events that are not directly triggered by a transaction. The problem are events that are directly triggered the transaction and mean the same thing which suggests to the user that for instance a transfer of tokens occurred twice - with the transaction and then with the event following the transaction

**Comment by lukeromanowicz** [comment]
I split the filtering issue to a separate task: https://github.com/aeternity/ae_mdw/issues/1523

In scope of this one let's discuss the possibility to expose AEX type, token symbol, and transfer value of AEX-9 and AEX-141 ContractCallTxEvent

**Comment by lukeromanowicz** [comment]
@sborrazas after discussing it in detail I think we should limit the requested feature in this issue to adding amount and preferably the symbol(so that we don't need to execute a second request) to the respective aexn events.

**Comment by janmichek** [comment]
Hi there, I took over this task after Luke.
Could you help me to state what else could be implemented? I saw it's partly resolved.

Is there a plan to add a collection name to ContractCallTxEvent related to AEX-141?
Should I close this or close and create some follow-up? Thanks for any update that may help .)

**Comment by sborrazas** [comment]
@janmichek this is indeed resolved. Token symbol, token_name, amount and decimals have all been added to aexn activities
