### ISSUE TITLE
Activities Count endpoint

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/ae_mdw#1506]
Please implement account activities count endpoint so we can use it for implementing pagination information and display it during browsing account activities =)

**Comment by sborrazas** [comment]
This feature, just like with any other endpoint that returns paginated list of things, would require major changes and will not be implemented for now

**Comment by janmichek** [comment]
This issue can be closed as there is no plan to implement it, right? Please close it, I don't have permission to do that.
