### ISSUE TITLE
sync with huge delay

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#153]
somehow there seems to be a huge delay in syncing with the node. in this example the middleware was 3 keyblocks behind:

```
{
  "mdw_height": 403531,
  "mdw_synced": false,
  "mdw_syncing": true,
  "mdw_tx_index": 20304063,
  "mdw_version": "1.0.2",
  "node_height": 403534,
  "node_progress": 100,
  "node_syncing": false,
  "node_version": "5.6.3"
}
```

is this a known issue or is this just related to the current deployment? I see that `v1.0.3` is already released. wondering why it isn't deployed yet.

**Comment by skkw** [comment]
This was caused because generations 403532 and 403533 are empty (no micro blocks and transactions inside).
The status is derived from the last stored transaction and that happened in generation 403531.
