### ISSUE TITLE
Make token search case insensitive

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1549]
The search results from endpoint `/v2/aex9?prefix=${query}` are sensitive for search query. 
It's not very user friendly and cannot be resolved on frontend

Extra points if you could add search by `symbol`. It's only possible to search by `name`

**Comment by janmichek** [comment]
The same insensitiveness would be nice to do for a search by NFT name/symbol

**Comment by yaboiishere** [comment]
Should this be the case for the aex141 endpoint?

**Comment by yaboiishere** [comment]
It's implemented for aex9 and aex141. Also it's already possible to search by the symbol, just isn't documented. I've updated the swagger spec. The way it's implemented is that the prefix or exact parameter works for symbols or names depending on the value of the 'by' parameter. By default it's name, so it works for the names if 'by' isn't passed

**Comment by janmichek** [comment]
Good job! When do you plan to deploy this?

**Comment by yaboiishere** [comment]
I hope I'll be done with it soon, Valentin found a pretty big issue with the way I was doing this and I've had to create a new table, which introduced some new problems with the request.

**Comment by janmichek** [comment]
It seems to work now. Do you plan to work on it?

**Comment by yaboiishere** [comment]
It's done, I've forgotten to give an update here
