### ISSUE TITLE
automate bumping version for release tag

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#155]
it seems like the middleware returns `1.0.3` instead of `1.0.4` as version on the `/status` endpoint. hopefully you can avoid this in the future. I think this is the second time this happened.

maybe you can automate that? @skkw

**Comment by thepiwo** [comment]
I think the issue itself is fixed, but I agree we should automate that

**Comment by jyeshe** [comment]
Fixed with Release Please by #228
