### ISSUE TITLE
operationIds misses entity name

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#156]
for example,
```json
    "/names/owned_by/{id}": {
      "get": {
        "deprecated": false,
        "description": "Get name information for given acount/owner",
        "operationId": "get_owned_by",
```
from https://mainnet.aeternity.io/mdw/swagger/swagger.json
shouldn't `operationId` contain `names` (like, `get_names_owned_by`)? Won't we have any other entities that can be owned by somebody?

**Comment by skkw** [comment]
Feature wise there probably won't be any other entities owning others. 
Oracles come close, but there's 1-1 mapping on the protocol level. (1 account can operate exactly one oracle, identified by the same pubkey as account)...
