### ISSUE TITLE
Enpoint returning inactive names for the account

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/ae_mdw#157]
We've need such thing to use in the wallet, to make user experience more user friendly.

**Comment by marc0olo** [comment]
@CedrikNikita can you specify a bit more what should be returned or what you want to achieve with that endpoint? currently this could be misinterpreted I think.

thoughts:
- is this just needed to show the users which names they have owned in the history but aren't owner of anymore?
- what if the "inactive" name is already claimed again by someone else? should the name still be returned or not?

**Comment by CedrikNikita** [comment]
We may have an endpoint that returns inactive names, that will accept the following parameters:
1. period of time - all inactive names that were lost within period of time
2. address - that will filter inactive names of a user
That may have some intresting outcomes:
1. We may inspire users to extend their names
2. Lost name won't disappear from wallet for a while, would be more userfriedly (when someone will claim the name you've lost, it will disappear from list)
3. We may have an intresting list of inactive names inside mdw
4. Lost names that someone once claimed, may be more intresting for the user

This vision of this issue was provided by @davidyuk
