### ISSUE TITLE
NFTs sorting by name on case insensitve mode

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1588]
There is obviously an issue with sorting by name. The names are not alphabetically sorted. Apparently, the case sensitivity of the first character is responsible for changing the order.

https://mainnet.aeternity.io/mdw/v2/aex141?limit=100&direction=forward&by=name

![image](https://github.com/aeternity/ae_mdw/assets/15363559/d78b5bcb-b969-41e7-add9-e6a45116ff4d)

**Comment by jyeshe** [comment]
Currently on lexicographical order.

**Comment by yaboiishere** [comment]
This should be fixed in #1836
