### ISSUE TITLE
Ability to view transctions in last 24h

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1593]
For the feature we are building
![image](https://github.com/aeternity/ae_mdw/assets/15363559/393ecfd3-468d-4299-aad7-93eecb93afa1)

We would like to show stats of txs last 24h with an increment.

The current solution https://staging.mdw.mainnet.aeternity.io/mdw/v3/statistics/transactions only giving day resolution. That mean If I compare last 2 entries, they are separated by midnight time, not an 24h window.

So the proposed solution is
1. add hour resolution filtering to https://staging.mdw.mainnet.aeternity.io/mdw/v3/statistics/transactions
2. come up with a dedicated endpoint

**Comment by janmichek** [comment]
Or if there is another way how to request data using the endpoint, lemme know. The docs has not been released yet, as it is in staging status.

**Comment by sborrazas** [comment]
@janmichek I'll come up with a dedicated endpoint for this. Working on it ASAP
