### ISSUE TITLE
Wrong `schemes` value of swagger file on production

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#160]
https://mainnet.aeternity.io/mdw/swagger/swagger.json

shouldn't it be `["https"]` instead of `["http"]`?

**Comment by thepiwo** [comment]
I don't know whats best practice for that

**Comment by davidyuk** [comment]
Just to have `https` there if it is deployed over https

**Comment by marc0olo** [comment]
I left a comment about that here:
- https://github.com/aeternity/aesophia_http/issues/70#issuecomment-865188084

I guess there are two options:
- remove the schemes section in the swagger definition
- add `https` additionally

but that's just an assumption. haven't verified

**Comment by marc0olo** [comment]
wondering about how that swagger file is generated? can we make it so that the `schemes` section is omitted? I think in the past the swaggerfile was included in the repo. doesn't seem to be the case anymore

**Comment by thepiwo** [comment]
closing in favour of general swagger improvements issue
