### ISSUE TITLE
Dex trades listing

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1603]
We would like to get a list of trade activities per token

Example
![image](https://github.com/aeternity/ae_mdw/assets/15363559/888ae75f-41ce-407a-a5f7-852eb9d5709c)

**Comment by jyeshe** [comment]
I am investigating an issue involving bonding curve deployment and can take it afterwards.

**Comment by janmichek** [comment]
Hi there, could we ask you for some time estimation for delivery? We would like to adjust our roadmap by this dependency.

**Comment by janmichek** [comment]
Thank you! Seems to be good. Can we identify the Buy/Sell activity from it?

**Comment by jyeshe** [comment]
> Thank you! Seems to be good. Can we identify the Buy/Sell activity from it?

https://github.com/aeternity/ae_mdw/issues/1603

**Comment by jyeshe** [comment]
> Thank you! Seems to be good. Can we identify the Buy/Sell activity from it?

For that, it should be provided the contract id of the DEX and the structure/declaration of both events.
