### ISSUE TITLE
Dex trades general listing

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1611]
Please expose the endpoint listing all dex trades

**Comment by jyeshe** [comment]
> Please expose the endpoint listing all dex trades

Could you provide the list of contracts (addresses) for `ae_uat` and `ae_mainnet`? If not possible, which other criteria should we consider to classify an AEX9 transfer as a DEX trade?

**Comment by janmichek** [comment]
@michele-franchi ?

**Comment by michele-franchi** [comment]
@jyeshe @janmichek these are the DEX contracts:

https://github.com/aeternity/dex-contracts-v2#aeternity-deployed-contracts

**Comment by vatanasov** [comment]
As per discussion with the aescan team, a route getting the swaps by contract id will be implemented.

**Comment by janmichek** [comment]
How long does it usually take from a swap on dex to be projected into the response? @vatanasov

**Comment by vatanasov** [comment]
It should be the time it takes for the mdw to sync with the node.

**Comment by janmichek** [comment]
Which should usually be...?

**Comment by vatanasov** [comment]
It should usually be almost instant.
