### ISSUE TITLE
Names statistics

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1612]
Please provide data for activated names (or claimed names) charts. Chart displays total number of names on time axis

**Comment by janmichek** [comment]
EDIT: It should display names activated per time unit (day, week, month)

**Comment by janmichek** [comment]
The data seems to be somehow incomplelte
EG: https://mainnet.aeternity.io/mdw/v3/statistics/names?limit=100&interval_by=month
Could you check, please?

**Comment by sborrazas** [comment]
@janmichek this endpoint does not return intervals where count=0 and it looks like there's very few months where names where activated. Can you find a name that was activated outside of those months?

**Comment by janmichek** [comment]
I also noticed this for the other statistics endpoint. 
As a user I would expect the time axis is continuous and it's not skipping days or months when the value at given time period is 0. Why just not print 0 for a time period with 0 events?

I see this chart as non-intuitive
![image](https://github.com/aeternity/ae_mdw/assets/15363559/c3ad8376-3d26-47b1-a5f3-42f25bdc9425)

**Comment by janmichek** [comment]
And it's ultimately not true
![image](https://github.com/aeternity/ae_mdw/assets/15363559/38117db1-029b-499f-94f1-0fb057d5f2e7)

https://mainnet.aeternity.io/mdw/v3/statistics/names?interval_by=day&limit=7
as for 7 days limit I get span values from 02/02 to 02/17

**Comment by sborrazas** [comment]
> And it's ultimately not true ![image](https://private-user-images.githubusercontent.com/15363559/310788955-38117db1-029b-499f-94f1-0fb057d5f2e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTkwNDUsIm5iZiI6MTcxMTQ1ODc0NSwicGF0aCI6Ii8xNTM2MzU1OS8zMTA3ODg5NTUtMzgxMTdkYjEtMDI5Yi00OTlmLTk0ZjEtMGZiMDU3ZDVmMmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEzMTIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzN2MwYWE3YjI0Zjg4NjI1YzI3YmNiZDM0Yzc5MmViMWRhOTcwZTRmOWUwM2JkZjViZmU0OGUxNzVkZGRlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NUFWqbhuiespqEagtYCH7rYuWw2iIQ4cYzGV_VQI9LE)
> 
> https://mainnet.aeternity.io/mdw/v3/statistics/names?interval_by=day&limit=7 as for 7 days limit I get span values from 02/03 to 02/20

The limit, as with any other endpoint, is the limit of results, not a filter. To filter by date you can use `min_start_date=2021-01-01` and/or `max_start_date=2021-02-02` as an example

**Comment by janmichek** [comment]
Then the question is why was the effort made for this feature?
Of course, we want to use this to display the last eg 7 days, not last 7 records for the chart.
I understand that we can implement this as you advised bringing some more logic to frontend.
In my eyes, it's imitating the backend logic that would find better place in mdw.
In that case, all the interval logic will be left unused. Is that how you want to proceed?

**Comment by sborrazas** [comment]
> Then the question is why was the effort made for this feature? Of course, we want to use this to display the last eg 7 days, not last 7 records for the chart. I understand that we can implement this as you advised, bringing some more logic to frontend. In my eyes, it's imitating the backend logic that would find better place in mdw. In that case, all the interval logic will be left unused. Is that how you want to proceed?

This endpoint is the only endpoint that returns up to 1000 results (when you set limit=1000), so we wanted to make sure we could improve its efficiency as much as possible by reducing the results that were bogus. Specially since we know some of these stats endpoints are used on every visit to aescan. 

Right now the returned result also matches what we store in the database (we don't store count=0), so we would need to use the same simple logic the frontend needs right now to include skipped results. 

Perhaps what we can try is to implement returning 0-value results and see how the server can cope with this, it might not be much at the beginning, but if it is we will have to go back to the current approach. Does that sound good to you @janmichek ?

**Comment by janmichek** [comment]
> > Then the question is why was the effort made for this feature? Of course, we want to use this to display the last eg 7 days, not last 7 records for the chart. I understand that we can implement this as you advised, bringing some more logic to frontend. In my eyes, it's imitating the backend logic that would find better place in mdw. In that case, all the interval logic will be left unused. Is that how you want to proceed?
> 
> This endpoint is the only endpoint that returns up to 1000 results (when you set limit=1000), so we wanted to make sure we could improve its efficiency as much as possible by reducing the results that were bogus. Specially since we know some of these stats endpoints are used on every visit to aescan.
> 
> Right now the returned result also matches what we store in the database (we don't store count=0), so we would need to use the same simple logic the frontend needs right now to include skipped results.
> 
> Perhaps what we can try is to implement returning 0-value results and see how the server can cope with this, it might not be much at the beginning, but if it is we will have to go back to the current approach. Does that sound good to you @janmichek ?

Yea, from your description sounds like what we want. You can first try it to implement it on names statistics, where the issue is present. The other endpoints does not have the same issue as there are plenty of records in given time event.

**Comment by sborrazas** [comment]
This is now on production https://testnet.aeternity.io/mdw/v3/statistics/names

**Comment by janmichek** [comment]
Perfect, now the chart makes complete sense 👍
