### ISSUE TITLE
Smart Contract Calls statistics

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1613]
Please provide data for contract call charts. Chart displays number of calls per time unit

**Comment by sborrazas** [comment]
@janmichek you can access this statistic by filtering `tx_type=contract_call` on transactions statistics endpoint:

https://mainnet.aeternity.io/mdw/v3/statistics/transactions?tx_type=contract_call&limit=1000

**Comment by janmichek** [comment]
@sborrazas ping

**Comment by sborrazas** [comment]
@janmichek it does not
