### ISSUE TITLE
NFT creation time entry

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1614]
Please add creation time and block value to the response from `/aex141/{id}` so we can display it in detail.

Please add the ability to sort NFT listing by creation `/aex141` (block value should be enough)

**Comment by vatanasov** [comment]
@janmichek by `block value` do you mean the block hash? And also the paths provided seem to be the same, could you specify which should be the second one?

**Comment by janmichek** [comment]
> @janmichek by `block value` do you mean the block hash? And also the paths provided seem to be the same, could you specify which should be the second one?

Correct, I improved the requirements. My bad, sorry. Now it should be clear .)

**Comment by janmichek** [comment]
Sorry I misunderstood your last question

**Comment by vatanasov** [comment]
No worries. Do you need to block hash, or should I remove it?

**Comment by janmichek** [comment]
block hash is not needed

**Comment by janmichek** [comment]
Looks great, thank you!
