### ISSUE TITLE
Token statistics

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1615]
Display how many transfers of tokens happened per time unit (day, week, month)

**Comment by janmichek** [comment]
Also please consider selecting custom date range which will be called through API

**Comment by vatanasov** [comment]
This issue seems to be similar to this one: https://github.com/aeternity/ae_mdw/issues/1896, is there any difference, @janmichek ?

**Comment by janmichek** [comment]
Yeah, looks like duplicate. THanks for a bump. Closing this
