### ISSUE TITLE
Make search for names case insensitive

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1651]
Currently the MDw returns only exact match. Please extend

https://github.com/aeternity/ae_mdw/assets/15363559/98c3e474-c907-40b8-b211-a5d50d8ec638

**Comment by janmichek** [comment]
https://mainnet.aeternity.io/mdw/v2/names/search?prefix=next
vs
https://mainnet.aeternity.io/mdw/v2/names/search?prefix=Next

**Comment by sborrazas** [comment]
@janmichek you should now be able to search case-insensitive via the /names endpoint https://mainnet.aeternity.io/mdw/v3/names?prefix=Next&by=name

**Comment by janmichek** [comment]
Looks good, thanks!
