### ISSUE TITLE
transaction in last 24H trend

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1654]
As an extension of https://github.com/aeternity/ae_mdw/pull/1623 I would like to request adding a value for a daily trend. Ideally expose  directly counted the percentage increment instead of last 48h to last 24h window count

for this feature:
![image](https://github.com/aeternity/ae_mdw/assets/15363559/5f7e4880-f4ca-463a-9591-79db76a2cccf)

**Comment by sborrazas** [comment]
@janmichek this was now added to the /stats endoint, where you can see the transactions count in the last 24h and the trend  compared to the previous 48hs

**Comment by janmichek** [comment]
Thanks, already grabbed this and implemented
