### ISSUE TITLE
Wrong `schemes` value of swagger file on production

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1668]
reopening https://github.com/aeternity/ae_mdw/issues/160

As I see it wasn't been fixed, both https://testnet.aeternity.io/mdw/api and https://testnet.aeternity.io/mdw/swagger/swagger.json contains
```
  "schemes": [
    "http"
  ],
```
which makes https://www.npmjs.com/package/swagger-client to request over `http` with error

> Access to XMLHttpRequest at 'http://testnet.aeternity.io/mdw/status' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Also, I assume it would fail with the mixed content error if the aepp would be opened over https.

**Comment by sborrazas** [comment]
@davidyuk this is now fixed, can you check and close this issue if so?

**Comment by davidyuk** [comment]
It looks good on testnet.aeternity.io, but if I run mdw locally, without https reverse proxy, the `"schemes"` value would be again wrong, wouldn't it?

**Comment by sborrazas** [comment]
That's right, you would have to manually update it on the `priv/static/swagger/` directory

**Comment by davidyuk** [comment]
https://github.com/aeternity/aesophia_http/pull/74/files

Some time ago we had the same issue with aesophia_http, we just removed `"schemes"` property and it looks fine so far. I would prefer this option, to don't edit `priv/static/swagger/` manually.

**Comment by sborrazas** [comment]
Removed now
