### ISSUE TITLE
mdw exposes logs for incorrect contract when using remote contract calls

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#167]
Doing a remote contract call, where the remote contract has an event logged, we receive the following from the node, where each event is related to the contract it did occur in.

![image](https://user-images.githubusercontent.com/6539235/117643977-47501a80-b189-11eb-900f-ee8aa381d403.png)

Mdw exposes both events logs for the originating contract of the remote call.

https://testnet.aeternity.io/mdw/contracts/logs/forward?contract_id=ct_2wGJdiQ2yVhnL4pM2ugDEPv8sJVi9oMNvGa3HUThmVdm35x2sV

**Comment by nikita-fuchs** [comment]
A big thanks to @genievot (why can't I tag him here? ) for discovering and reporting.

**Comment by thepiwo** [comment]
If you need more example contact me

**Comment by thepiwo** [comment]
other test data:

https://testnet.aeternity.io/mdw/contracts/logs/forward?contract_id=ct_2qaCW3Aok5EyX6Gochn7sXQkfBTLoQyccKigZgeFJJhwD4zi3

https://testnet.aeternity.io/v2/transactions/th_UksVPnE8fuYggjsh5J43dQfK7g3ZSeX5LFC5GtakkF5NRc9qz/info

created from contracts:
```
contract Example1 =
  datatype event = Event1(string)

  entrypoint exampleEvent1() = 
    Chain.event(Event1("1"))
```

```
contract interface Example1 =
  entrypoint exampleEvent1 : () => unit
  
main contract Example2 =
  datatype event = Event2(string)

  entrypoint exampleEvent2(c : Example1) =
    c.exampleEvent1()
    Chain.event(Event2("2"))
```

**Comment by jyeshe** [comment]
[two_contrUacts.zip](https://github.com/aeternity/ae_mdw/files/7015749/two_contracts.zip)

**Comment by jyeshe** [comment]
For each contract, the first two logs are from emitEvent():
https://testnet.aeternity.io/mdw/contracts/logs/forward?contract_id=ct_iyVsmYF3iZnFs4NTssceBMMFFMoQDoraoYRfjwDFbUyJU5pdT
https://testnet.aeternity.io/mdw/contracts/logs/forward?contract_id=ct_8xw9cfgtrDEGdUuJeh6tJRYcf2MBcZAwunBmpfSCd7h5QCwVu

Calling emitBothEvent() is raising:
emitBothEvents - call errored: Error: Invocation failed Most likely there is a syncing issue in the load balanced testnet nodes, please re-deploy the contract and try again.
![image](https://user-images.githubusercontent.com/44991200/130099593-9bda6c73-3565-4792-8794-adba7d92a043.png)

**Comment by jyeshe** [comment]
Reproduced:
![image](https://user-images.githubusercontent.com/44991200/130111859-121aa95a-c56e-4de6-9782-8db8e52d9bfa.png)
