### ISSUE TITLE
function name and params missing on failed contract calls

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/ae_mdw#1713]
Hey, as discussed on Slack:

Good case: https://aescan.io/transactions/th_p2Bqd4Qgp2G5d4XUNE6qYnb48X2R6PRTEs9UugMVsczHim8Hk 
(call succeeded, function name and call params stored and shown)

Bad Case:
https://aescan.io/transactions/th_2FyTGu6zQKTpbVewcHLpdrsqz6jT6jyWk5cXwrV4cAuAPnEhY9
(call reverted, function name is `<unknown>` , tx params not shown)

You can verify that they both have the same call data: cb_KxGJwsZPG2+JBQqiX0PPU//AlZ0P4w==

It makes debugging failed calls harder, as the mdw does not serve any of the necessary information in this case. People don't know what function they called and with what input.

**Comment by nikita-fuchs** [comment]
Apparently, the node does not provide this particular information: https://mainnet.aeternity.io/v3/transactions/th_2FyTGu6zQKTpbVewcHLpdrsqz6jT6jyWk5cXwrV4cAuAPnEhY9

**Comment by sborrazas** [comment]
This is now updated, reverted calls are going to show the function name and args, but not the result of calling it because it wasn't executed
