### ISSUE TITLE
Make and npm has to be installed on the environment before installing, should be on dependencies setup guide

### ISSUE THREAD

**Issue by omar-saadoun** [aeternity/ae_mdw#175]
While installing on ubuntu by following the setup guideline we should add that make needs to be installed before:

root@inmindUbuntu1804:/home/inmind/ae_mdw# ls
config              erlang-solutions_2.0_all.deb  Makefile   priv
docker              frontend                      mix.exs    README.md
docker-compose.yml  keys                          mix.lock   test
Dockerfile          lib                           notes.txt
root@inmindUbuntu1804:/home/inmind/ae_mdw# make compile

Command 'make' not found, but can be installed with:

apt install make      
apt install make-guile

Same happens for npm

**Comment by thepiwo** [comment]
we should remove the frontend from this repository
