### ISSUE TITLE
Accept `/mdw` path in the container ENV variable

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1759]
Currently, at https://mainnet.aeternity.io/mdw/v2/api we have
```json
"servers": [{
  "url": "/mdw/v2",
  "description": "V2 version path"
}],
```
which is correct, but when I'm running mdw image locally at http://localhost:4000/v2/api there are still
```json
"servers": [{
  "url": "/mdw/v2",
  "description": "V2 version path"
}],
```
It is incorrect, it should be just `/v2`. I see several ways to solve it.
- try the relative url, like `./`, not sure if is it supported by clients
- try to guess the right server url by a request url, like if openapi is requested at http://example.com/path/to-mdw/v2/api then `servers[0].url` should be `/path/to-mdw/v2`
- accept mdw path in ENV variable, so it should be set correctly according to the environment

The last way assumes openapi spec should be served by a handler that would substitute the path to mdw in runtime. This seems to be the most easy way.

**Comment by vatanasov** [comment]
Solved in #1837, there is a `PATH_PREFIX` ENV variable now.
