### ISSUE TITLE
Name appears in both auctions and expired listing

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1778]
look for `meta.chain`

https://mainnet.aeternity.io/mdw/v2/names?cursor=g2gCYgAOS4VtAAAACm1ldGEuY2hhaW4&expand=true&limit=10&state=inactive

https://mainnet.aeternity.io/mdw/v2/names/auctions?by=expiration&direction=forward&limit=10

**Comment by vatanasov** [comment]
The name does appear in both listings, but the auction is also inactive. Do you remember if it was active when you posted the issue?

**Comment by janmichek** [comment]
> The name does appear in both listings, but the auction is also inactive. Do you remember if it was active when you posted the issue?

Hello, you can still see it here

https://mainnet.aeternity.io/mdw/v2/names/auctions?by=expiration&direction=forward&limit=10

https://mainnet.aeternity.io/mdw/v2/names?cursor=g2gCYgAOUv5tAAAAF3hpYW9taWNvcnBvcmF0aW9uLmNoYWlu&expand=true&limit=10&state=inactive

If the name is auction but inactive, I would expect it to be Expired then. Or how many states for a name are there?

**Comment by vatanasov** [comment]
So it seems like when a name becomes inactive, that makes it available for auctions. So when such name is auctioned, it would appear in both listings (which apparently happened for the `meta.chain` name).

**Comment by janmichek** [comment]
@michele-franchi do you have any idea how to approach this?

**Comment by janmichek** [comment]
Apparently, the name can have multiple statuses. We will have to re-iterate the whole Names page and detail concept

**Comment by janmichek** [comment]
So to make thing clear the 1 name can have following states which are 1:N

- Active
- In Auction
- Expired
- Expired & In Auction

Are there some other possible combinations?

**Comment by vatanasov** [comment]
I think so, yes. @sborrazas can you confirm?

**Comment by sborrazas** [comment]
Yes, that is correct. We call expired names "inactive", but those are indeed the 4 states a name can have

**Comment by janmichek** [comment]
thanks for explanation. Will adjust in aescan
