### ISSUE TITLE
`get_owned_by` should contain `names`

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#179]
I don't agree with the resolution of #156

Even if it doesn't have collisions, operation names should be correct and clear as far as they may be used by API generators and exposed to developers as they are.

For example, if sdk in the future would create an API wrapper of middleware, it doesn't need to apply fixes of naming initially introduced in middleware.

**Comment by thepiwo** [comment]
feel free to reopen with futher information if this still applies

**Comment by davidyuk** [comment]
@thepiwo nothing changed here as I see, but I don't have "Reopen" button, can you do it for me?

**Comment by sborrazas** [comment]
This is done and will be deployed on the next release.

**Comment by sborrazas** [comment]
This change will break SDK/wallet usage, for we're reverting it for now. 

Ultimately a new swagger file containing all v2 operations and operation name updates will be created.

**Comment by sborrazas** [comment]
Getting names owned by a user is no longer a separate swagger operation. Now it simply uses the regular `/v2/names` route filtered by owned_by (e.g. `/v2/names?owned_by=ak_...`). So this operation rename no longer applies. Should we close it @davidyuk ?

**Comment by davidyuk** [comment]
I think so, thank you!
