### ISSUE TITLE
Docker startup fails possibly because ipv6 is disabled on host.

### ISSUE THREAD

**Issue by jagguli** [aeternity/ae_mdw#1803]
[error] Failed to start Ranch listener 'Elixir.AeMdwWeb.Endpoint.HTTP' in ranch_tcp:listen([{cacerts,'...'},{key,'...'},{cert,'...'},{ip,{0,0,0,0,0,0,0,0}},{port,4000}]) for reason eafnosupport (address family not supported by protocol family)

```
docker-compose -f docker-compose.yml up
```

**Comment by yaboiishere** [comment]
Hey, I can't seem to reproduce this, can you give me some more info about your system, like what OS are you running on and stuff like that? Also have you changed anything in the repo before running the command?

**Comment by jagguli** [comment]
Hi I got it working after I changed the ip to ```ip: {0, 0, 0, 0}``` 
I'm on archlinux, docker  26.1.3 
I have ipv6 disabled through kernel param

**Comment by yaboiishere** [comment]
Maybe there can be an Env variable that can be set, so that the endpoints can start on ipv4 addresses?

**Comment by jagguli** [comment]
Works good with the env flag, thanks!
