### ISSUE TITLE
Pass next url through HTTP headers

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#181]
https://testnet.aeternity.io/mdw/txs/forward

Currently have this structure:
```
{
  "data": [{
    "hash": ...,
    ...
  }, ...],
  "next": "txs/gen/0-443535?limit=10&page=2"
}
```

If we would generate an API wrapper around this we'll get something like:
```
api.get_txs_by_direction('forward').data[n].hash
```

`next` is related to metadata and storing it with actual returned data makes us wrap it with an extra useless object. To avoid that we can pass `next` in response headers, removing the extra wrapper. Then generated interface would be simpler:
```
api.get_txs_by_direction('forward')[n].hash
```

So, to simplify middleware interface I'm proposing to pass `next` in an HTTP response header like:
```
Next-Page-Path: /txs/gen/0-443535?limit=10&page=2
```

Response headers are easily accessible in `fetch` response in JS:
```
const response = await fetch('https://testnet.aeternity.io/mdw/txs/forward')
response.headers.get('Next-Page-Path')
```

Also Swagger supports types for response headers: https://swagger.io/docs/specification/describing-responses/#headers

**Comment by davidyuk** [comment]
> I am not sure if developers are expecting these kinds of information via params in the header. personally I don't see a problem providing this data in the response.

@marc0olo I agree that it works both ways, but metadata suits more for headers than the response body. As a developer asking for transactions I would expect to receive an array of them than the array wrapped with an object for the use case that is not strictly necessary.

**Comment by marc0olo** [comment]
first of all the dev should expect the response which the API specification provides :-)

now it's up to us to decide the way we want to provide it. my personal opinion is that it's more convenient in case of pagination to have that information provided in the response similar to sth. like this:
```
{
    "data": [
        {...},
        {...},
    ],
    "paging": {
        "previous":  "/txs/gen/0-443535?limit=10&page=1"
        "current": "/txs/gen/0-443535?limit=10&page=2"
        "next": "/txs/gen/0-443535?limit=10&page=3"
    }
}
```

**Comment by davidyuk** [comment]
> should expect the response which the API specification provides

for sure, but API developer may make it more intuitive😉

The idea is to make API semantic avoiding meaningless stuff like "data" 🤷‍♀️

Architecturally something wrong with this next/current/prev URLs. Maybe we can avoid it in general? Like, make a scope (`<from block>_<to block>`) a required parameter asking developer to track it by himself.

The current implementation looks like an endless failback: "you can use pagination API (without scope), but it won't work fine (#106) and be always asking you to switch to the proper API by providing prev/current/next URLs".

**Comment by the-icarus** [comment]
@davidyuk With your proposal moving the responsibility to the developer I see on issue doing it based on a block. AFAIK the number of txs per block is not fixed which would end up in dynamic page size which is more complex to handle. I would rather prefer a stable page size. But in such a case we should still need to provide the information on how many pages with the current page size exist or the total number on transactions in the system so the developer can calculate the total number of pages.

**Comment by thepiwo** [comment]
I think our current implementation is fine, if this discussion should be revived, feel free to open again with some arguments
