### ISSUE TITLE
Internal error when fetching a dex swap

### ISSUE THREAD

**Issue by vatanasov** [aeternity/ae_mdw#1810]
https://mainnet.aeternity.io/mdw/v3/dex/ct_azbNZ1XrPjXfqBqbAh1ffLNTQ1sbnuUDFvJrXjYz7JQA1saQ3/swaps returns an internal server error. It seems to be, because there is not a corresponding entry in the `:dex_pairs_symbols` table.

**Comment by sborrazas** [comment]
Fixed
