### ISSUE TITLE
Add further fields to swap endpoint

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1815]
Please add following fields to 
`/dex/swaps`

action: [BUY | SELL | SWAP]
fromContract: [contractId]
toContract: [contractId]
fromAmount: [number]
toAmount: [number]
fromDecimals: [number]
toDecimals: [number]
microtime(of the tx): [time]
height (of the tx): [number]

also please document the API docs

**Comment by vatanasov** [comment]
@janmichek can you elaborate on:

1. What do you mean by the `action` field? Which swaps do you consider buy/sell?
2. With `fromContract` and `toContract` do you mean the sender and receiver accountPK?

**Comment by janmichek** [comment]
>     1. What do you mean by the `action` field? Which swaps do you consider buy/sell?

I think you will get it by the entrypoint `swap_exact_ae_for_tokens` in this case th_2MZcRcm9Rcjf6HFoxjtHgPVAQSLurLQSFqJ6zjZew5sk7jPU7u

>     2. With `fromContract` and `toContract` do you mean the sender and receiver accountPK?

By this I mean the token contract adresses

**Comment by janmichek** [comment]
Ok, great, the response for general swaps looks complete.
But how its the response for swaps per token? eg https://testnet.aeternity.io/mdw/v3/dex/ct_BGSnJnxuCgQx9kz4PW3u3JcwrjVAZ4xLKv8Bfi9ce5xygVK7Q/swaps?limit=10
It was working before, but now it stopped working. So I am not sure what's in the response.

**Comment by janmichek** [comment]
> Ok, great, the response for general swaps looks complete. But how its the response for swaps per token? eg https://testnet.aeternity.io/mdw/v3/dex/ct_BGSnJnxuCgQx9kz4PW3u3JcwrjVAZ4xLKv8Bfi9ce5xygVK7Q/swaps?limit=10 It was working before, but now it stopped working. So I am not sure what's in the response.

Can you check this regression, please? It was working before.

**Comment by vatanasov** [comment]
Yes, we are working on fixing it.

**Comment by janmichek** [comment]
Hello, do you have any updates on this? @vatanasov

**Comment by vatanasov** [comment]
@janmichek, some things will be improved in the next release (all the contracts in the `v3/dex/swaps` page should shall correctly their swaps on `/v3/dex/<contract-id>/swaps` page), but there are still some lingering issues we are working on.

**Comment by janmichek** [comment]
It seems to work now. Or do you plan any changes?

**Comment by vatanasov** [comment]
> Ok, great, the response for general swaps looks complete. But how its the response for swaps per token? eg https://testnet.aeternity.io/mdw/v3/dex/ct_BGSnJnxuCgQx9kz4PW3u3JcwrjVAZ4xLKv8Bfi9ce5xygVK7Q/swaps?limit=10 It was working before, but now it stopped working. So I am not sure what's in the response.

Yes, there are more things to be done, the example you mentioned here isn't working yet.

**Comment by janmichek** [comment]
Looks fixed now and nicely documented. Good job!
