### ISSUE TITLE
Contract events count does not work after migration

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1816]
https://mainnet.aeternity.io/mdw/v2/aex9/ct_J3zBY8xxjsRr3QojETNw48Eb38fjvEuJKkQ6KzECvubvEcvCa/logs-count
146

vs

https://mainnet.aeternity.io/mdw/v3/aex9/ct_J3zBY8xxjsRr3QojETNw48Eb38fjvEuJKkQ6KzECvubvEcvCa/logs-count
no such route

**Comment by janmichek** [comment]
same for 
https://mainnet.aeternity.io/mdw/v2/aex9/account-balances/ak_2mK4SipNeUcsw5fAzvn2rgzP1GRVo9w4VdRUD5ZLH2otXfaMUy?limit=10
vs
https://mainnet.aeternity.io/mdw/v3/aex9/account-balances/ak_2mK4SipNeUcsw5fAzvn2rgzP1GRVo9w4VdRUD5ZLH2otXfaMUy?limit=10

**Comment by sborrazas** [comment]
The logs count you can access the on the listing endpoint (or detail) as such: https://mainnet.aeternity.io/mdw/v3/aex9/ct_TEt8raHSNKZWHNN8TaCvV2VKDuSGPcxAZhNJcq62M8Gwp6zM9

For the account balances, you can access them on the accounts endpoints: https://mainnet.aeternity.io/mdw/v3/accounts/ak_YCwfWaW5ER6cRsG9Jg4KMyVU59bQkt45WvcnJJctQojCqBeG2/aex9/balances

**Comment by janmichek** [comment]
> The logs count you can access the on the listing endpoint (or detail) as such: https://mainnet.aeternity.io/mdw/v3/aex9/ct_TEt8raHSNKZWHNN8TaCvV2VKDuSGPcxAZhNJcq62M8Gwp6zM9


THis does not seems to be right. the 
https://mainnet.aeternity.io/mdw/v3/aex9/ct_2fupR8bdFyiA1dtFqeShfRh96vvxeAPFopz7eS8zRfpRdgBruQ
logs_count does not match with 

https://mainnet.aeternity.io/mdw/v3/contracts/logs?contract=ct_2fupR8bdFyiA1dtFqeShfRh96vvxeAPFopz7eS8zRfpRdgBruQ&aexn-args=true&limit=10
the count of events

Can you check it please?



> For the account balances, you can access them on the accounts endpoints: https://mainnet.aeternity.io/mdw/v3/accounts/ak_YCwfWaW5ER6cRsG9Jg4KMyVU59bQkt45WvcnJJctQojCqBeG2/aex9/balances

Good suggestion, thanks
