### ISSUE TITLE
Different name fee from different verison

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1818]
There is a significantly different name price
![image](https://github.com/aeternity/ae_mdw/assets/15363559/4422fba6-37eb-4181-9490-035aa46ab262)
vs
![image](https://github.com/aeternity/ae_mdw/assets/15363559/017cbf89-8b09-4218-9554-47125119f5a6)

https://mainnet.aeternity.io/mdw/v2/names?state=active&expand=true&by=deactivation&direction=forward&limit=10
vs
https://mainnet.aeternity.io/mdw/v3/names?state=active&expand=true&by=deactivation&direction=forward&limit=10

**Comment by sborrazas** [comment]
The name_fee attribute represents the current fee cost of claiming that name, which increases over time: https://github.com/aeternity/aeternity/blob/master/apps/aecore/src/aec_governance.erl#L349

**Comment by janmichek** [comment]
thanks for explanation
