### ISSUE TITLE
Make endpoints consistent named with Aeternity node

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#183]
can't reopen #109 see #180 

the same situation with `/txs/:hash` in middleware and `/trahsactions/:hash` in node

**Comment by marc0olo** [comment]
we should label all the issues related to consistency issues to ideally fix them all together in a future release cc @mradkov

**Comment by thepiwo** [comment]
@sborrazas @jyeshe did you have any thoughts on this?

**Comment by sborrazas** [comment]
I believe the naming of things and the way URLs are built is consistent with the names [from here](https://api-docs.aeternity.io/). Perhaps the only difference would be  the one listed here:`/transactions` in the node and `/txs` in mdw, we can change that easily for v2-v3

**Comment by thepiwo** [comment]
@sborrazas but we didn't to it in v2 right?

**Comment by sborrazas** [comment]
@thepiwo we didn't do it indeed

**Comment by sborrazas** [comment]
This was now added on v3
