### ISSUE TITLE
Links to current and previous pages as now for next page

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#184]
https://testnet.aeternity.io/mdw/txs/forward

Currently have this structure:
```
{
  "data": [{
    "hash": ...,
    ...
  }, ...],
  "next": "txs/gen/0-443535?limit=10&page=2"
}
```

Would be useful to have "absolute" links to current and previous pages as now we have for the next page.

Use case: In middleware frontend user may looks through several pages of transactions relative to blockchain top (by the index of page) and want to save link to the current page. After opening it later frontend should show the same transactions (they shouldn't be shifted by the recent ones) and also frontend should allow navigation to both previous and next pages.

**Comment by marc0olo** [comment]
you should keep in mind the other issue you opened #181 

I am not sure if developers are expecting these kinds of information via params in the header. personally I don't see a problem providing this data in the response.

what speaks against sth. like this?
```
{
    "data" : [
        {...},
        {...},
    ],
    "paging":  {
        "previous":  "/txs/gen/0-443535?limit=10&page=1"
        "current": "/txs/gen/0-443535?limit=10&page=2"
        "next": "/txs/gen/0-443535?limit=10&page=3"
    }
}
```

cc @mradkov

**Comment by davidyuk** [comment]
> you should keep in mind the other issue you opened

nope, headers is a separate issue, would be messy to combine them

**Comment by thepiwo** [comment]
next is now fully cursor based, `page` was never fully supported to go forwards or backwards, I will close this for now
