### ISSUE TITLE
How `page` is handled in `next` urls?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#185]
According to the discussion in https://github.com/aeternity/ae_mdw/issues/106#issuecomment-825489932 `next` path is an "absolute reference to the point of history", but `next` always contain originally passed `page` parameter that is a relative reference. Is the `page` parameter
- ignored in this case
- becomes relative to the scope of `next` path
- remains relative to the blockchain top?
 
Won't happen a case when `page` becomes pointing outside of the `next` scope because of newly mined transactions?

**Comment by thepiwo** [comment]
with the latest refactoring previously ignored `page` is now fully removed.
