### ISSUE TITLE
Swagger UI deployment misses v3 api

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1852]
In [README](https://github.com/aeternity/ae_mdw?tab=readme-ov-file#openapi-specs) there is a link to [swagger UI](https://testnet.aeternity.io/mdw/swagger).

<img width="716" alt="Screenshot 2024-07-22 at 23 51 35" src="https://github.com/user-attachments/assets/9f74afe4-99f5-4625-b7e3-8d8212c8dba0">

Would be good to add v3 api to the list.

**Comment by vatanasov** [comment]
Done, with the help of @venimus
