### ISSUE TITLE
Add a dash to `/deltastats`, `/totalstats`, `/minerstats`

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1856]
Like, `/delta-stats`, `/total-stats`, `/miner-stats`.
Because it is not a single word, and to be consistent with `/key-blocks`, `/micro-blocks`.

**Comment by sborrazas** [comment]
I'm renaming these to `/statistics/delta`, `/statistics/total` and `/statistics/miners` to follow the previous issue opened.
