### ISSUE TITLE
Remove `/names/count` because `/v3/totalstats` provides this data

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1857]
As I see [`/names/count`](https://mainnet.aeternity.io/mdw/v3/names/count) is the same value as `active_names` field in the last block of [`/v3/totalstats`](https://mainnet.aeternity.io/mdw/v3/totalstats). So, it can be removed to simplify the api.

**Comment by sborrazas** [comment]
This endpoint returns all name counts when not filtering by owned_by, which is indeed the same as totalstats. But the most common use case would be to actually use the filter. e.g. https://mainnet.aeternity.io/mdw/v3/names/count?owned_by=ak_2r2xGN1v8QKQDNk35WBKyH6Wxz1WP3pxhBNrLgeaK9aTybjvDL

**Comment by davidyuk** [comment]
Oh, I didn't notice that it accepts parameters, then it makes sense 👍
