### ISSUE TITLE
Add `/v3/stats` to Open Api

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1858]
Middleware has an endpoint [`/v3/stats`](https://mainnet.aeternity.io/mdw/v3/stats), but I can't find it definition in [`/v3/api`](https://mainnet.aeternity.io/mdw/v3/api)

**Comment by vatanasov** [comment]
Solved in https://github.com/aeternity/ae_mdw/pull/1863 (docs: https://mainnet.aeternity.io/mdw/swagger/#/default/GetStats)
