### ISSUE TITLE
endpoint for Deployed contracts chart

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1892]
Deployed contracts count aggregated by time

**Comment by yaboiishere** [comment]
Isn't that the "contracts" field in  https://mainnet.aeternity.io/mdw/v3/stats/total ?

**Comment by janmichek** [comment]
Yeah, I think you ar right. My bad, closing this

**Comment by janmichek** [comment]
I would like to have an endpoint with Deployed contracts aggregated by time

**Comment by janmichek** [comment]
@yaboiishere is it this the solution https://github.com/aeternity/ae_mdw/pull/1936 ?

**Comment by yaboiishere** [comment]
Yes

**Comment by janmichek** [comment]
Thank you, I will check that later and close the issue in the positive case .]

**Comment by yaboiishere** [comment]
Hey, can i close this? The docs are at:  https://mainnet.aeternity.io/mdw/swagger/#/default/GetContractsStats

**Comment by janmichek** [comment]
Thanks, Will check it and react
