### ISSUE TITLE
Migrate rest of NFT endpoints to v3

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1898]
https://testnet.aeternity.io/mdw/v2/aex141/transfers/ct_2UVjVLvt2NycqbfJWywixyYm68iVvkiVS9wubiQRjp9WeQtfpK?limit=10
to
https://testnet.aeternity.io/mdw/v3/aex141/transfers/ct_2UVjVLvt2NycqbfJWywixyYm68iVvkiVS9wubiQRjp9WeQtfpK?limit=10

and 

https://mainnet.aeternity.io/mdw/v2/aex141/ct_M14j2hVwDqSraKqwi9udj31NM4f3SGYPXC7UDVqKqfoeUUjX2/owners?limit=10
to
https://mainnet.aeternity.io/mdw/v3/aex141/ct_M14j2hVwDqSraKqwi9udj31NM4f3SGYPXC7UDVqKqfoeUUjX2/owners?limit=10

**Comment by yaboiishere** [comment]
In v3 I see 2 options, there is https://testnet.aeternity.io/mdw/v3/aex141/transfers?contract_id=ct_2UVjVLvt2NycqbfJWywixyYm68iVvkiVS9wubiQRjp9WeQtfpK which moves the contract_id from the path to a query argument and there is also https://testnet.aeternity.io/mdw/v3/aex141/ct_2UVjVLvt2NycqbfJWywixyYm68iVvkiVS9wubiQRjp9WeQtfpK/transfers which

**Comment by janmichek** [comment]
> In v3 I see 2 options, there is https://testnet.aeternity.io/mdw/v3/aex141/transfers?contract_id=ct_2UVjVLvt2NycqbfJWywixyYm68iVvkiVS9wubiQRjp9WeQtfpK which moves the contract_id from the path to a query argument and there is also https://testnet.aeternity.io/mdw/v3/aex141/ct_2UVjVLvt2NycqbfJWywixyYm68iVvkiVS9wubiQRjp9WeQtfpK/transfers which

I lean to the second option, but I will leave the final decision on you

**Comment by yaboiishere** [comment]
Oh no, I meant that they are already implemented :)

**Comment by janmichek** [comment]
@yaboiishere That only explains transfers. How about 'owners' ?

https://testnet.aeternity.io/mdw/v3/aex141/owners?contract_id=ct_2UVjVLvt2NycqbfJWywixyYm68iVvkiVS9wubiQRjp9WeQtfpK

https://testnet.aeternity.io/mdw/v3/aex141/ct_2UVjVLvt2NycqbfJWywixyYm68iVvkiVS9wubiQRjp9WeQtfpK/owners

**Comment by yaboiishere** [comment]
These seem to have been moved to https://testnet.aeternity.io/mdw/v3/aex141/ct_2UVjVLvt2NycqbfJWywixyYm68iVvkiVS9wubiQRjp9WeQtfpK/tokens

**Comment by janmichek** [comment]
Got it, thanks. All solved then
