### ISSUE TITLE
Alter response for certain contracts

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/ae_mdw#1899]
**The following request is approved by Nikola and is to be treated with highest priority.**

**The short story**: There are token contracts deployed for the ae bridge. They represent the bridged, 'wrapped' version of this token, on aeternity. People can wrap their USDT from Ethereum to Aeternity. This USDT is then to be called aeUSDT. The contracts deployed for this got names which sometimes are plain nonsense or just don't adhere to this formatting. Therefore, these bad names appear in the wallet, which lead to ** massive trouble** (explaining to you in slack).

**Todo**: The response to the requests of the _name_ of the token must be adjusted for those token contracts to adhere to a required uniform standard. One example: If the token's **name** on Ethereum is `TRON` and its **symbol** is `TRX`, the name for its wrapped counterpart shall be **aeTRON** and **aeTRX**.

Here is a list of contracts, to which this applies: https://github.com/aeternity/aepp-bridge/blob/68801cb2d5d97cfcdb5993e826dc42d88eaadfdd/src/chainConfig.ts#L36

The most attention belongs to the first one in this list, the **wrapped ethereum**, which got a super bad name ("Native Ethereum Placeholder" which was the starting point of it all).

Please don't hesitate to reach out to me with questions or concerns, either on slack or telegram. Thank you very much.

**Comment by nikita-fuchs** [comment]
LGTM !

**Comment by thepiwo** [comment]
this will be a pain in the future and backfire eventually, some applications might fetch that information from dry-running meta_info on-chain instead of getting it from mdw, then receive a different name and confuse users. If its just a UI issue, why change it in mdw?

**Comment by nikita-fuchs** [comment]
We know, the trade-off between this eventually becoming an issue one day and the consequences it has now was in favour of doing this, I personally also don't like it. But the chances that anyone else will ever interact with any of this directly through a contract are marginal, plus the "adjusted" naming is not far from the one in the contract. 

Don't get me wrong, not approving this technically, this had other reasons.
