### ISSUE TITLE
Accept name hash in auction endpoints to be consistent with name endpoints

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#1910]
I found out that GetName, GetNameClaims, GetNameTransfers, and GetNameUpdates accept name hash the same as a plain name. It would be consistent to support name hash in GetNameAuction, and GetNameAuctionClaims.

**Comment by yaboiishere** [comment]
This is deployed and is available https://petstore.swagger.io/?url=https://mainnet.aeternity.io/mdw/v3/api#/default/GetNameAuction
