### ISSUE TITLE
Add counting of transactions for specific account with scoping

### ISSUE THREAD

**Issue by vatanasov** [aeternity/ae_mdw#1943]
Aescan requires information about count of transactions for specific account with scoping by height. [/transactions/count](https://mainnet.aeternity.io/mdw/swagger/#/default/GetTransactionsCount) can't take two filters and [/accounts/{id}/transactions/count](https://mainnet.aeternity.io/mdw/swagger/#/default/GetAccountTransactionsCount) doesn't support filtering by height. Probably making the second one work would be more appropriate.

**Comment by janmichek** [comment]
For the feature I build for aescan, I would ideally filter by time. I would use 24hours window, actually.

**Comment by yaboiishere** [comment]
Would something similar to the way stats endpoint be ok for this?

**Comment by janmichek** [comment]
> Would something similar to the way stats endpoint be ok for this?

Yeah, is the 24h window also possible like this per account? That would be ideal

**Comment by yaboiishere** [comment]
I think so, but the database might become way bigger. I'll try to implement it and see how it performs

**Comment by yaboiishere** [comment]
@janmichek ping

**Comment by janmichek** [comment]
Hey, just got back from vacation. Will think about it and decide, thanks for the suggestion.

**Comment by janmichek** [comment]
This is what I want to achieve. How and which miners were active lately 

https://www.aeknow.org/miner



<img width="505" alt="image" src="https://github.com/user-attachments/assets/d3c3d742-8eb4-4e11-825b-acf8bf19b1b9">

**Comment by yaboiishere** [comment]
Hmm, this sounds like we would need to modify the `stats/miners` endpoint to function like the other ones where you would be able to filter by time intervals. How do you plan to use the transactions stats endpoint to get all the miners?

**Comment by janmichek** [comment]
Yeah, I should state whats my intention behind that. Sorry, at least we have it now .]
The solution would not be perfect ad would require some data transformation on frontend.
As much as you are able to pre process data for me for this chart above, the happier I will be .]]] 
I guess your last suggestion ( modify the stats/miners) seems good.

**Comment by yaboiishere** [comment]
In that case I think it would be best to leave this feature as it is and create a new issue about modifying the stats/miners or creating a new endpoint to provide the data as you need it

**Comment by janmichek** [comment]
you can close this one
