### ISSUE TITLE
improve docker builds

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#195]
think there are things that can be improved:

- [x] image size (node image uses ~145mb whereas the mdw including the node requires ~555mb)
- [x] file structure (I would appreciate if it reflects a similar folder structure as the node image at least for the node related stuff)
- [x] specify a specific user and that the containers of the image aren't running with root

ideally we have a more or less generic approach that can be applied to other plugins that make use of https://github.com/aeternity/ae_plugin

**Comment by sborrazas** [comment]
Additionally, we need to build the docker image using [Elixir releases](https://hexdocs.pm/mix/Mix.Tasks.Release.html) which will leave out the overhead from downloading the libraries repos. It will also optimize the image for faster startup.

**Comment by jyeshe** [comment]
Done after:
- #1190 
- #1197 
- #1199
