### ISSUE TITLE
Name status is missing after migration

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#1954]
https://mainnet.aeternity.io/mdw/v2/names/huhu.test
vs
https://mainnet.aeternity.io/mdw/v3/names/huhu.test

please add status to v3

**Comment by sborrazas** [comment]
It has an active field specifying if the name is active or not. And when it's not there's an auction field.
active: true => active name
active: false and auction: null => inactive name
active: false and auction != null => inactive name in auction

**Comment by janmichek** [comment]
That should be good then, thanks
