### ISSUE TITLE
search: paginated results & possibility to exclude `.test` names in the results

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#196]
when implementing the search in https://aenalytics.org we recognized that it is not a good idea to search for single characters which would happen when implementing search for dynamically typed text.

additionally it would be great to be able to exclude "deprecated" `.test` names in the response .

**Comment by thepiwo** [comment]
I think this is out of scope for mdw, you could filter `.test` names by not considering generations that were `.test` only
