### ISSUE TITLE
Contract transfers returning Internal Server Error

### ISSUE THREAD

**Issue by yaboiishere** [aeternity/ae_mdw#1968]
Aex141 contract transfers are returning internal server errors. 

https://mainnet.aeternity.io/mdw/v3/aex141/ct_2t7TnocFw7oCYSS7g2yGutZMpGEJta6dq2DTX38SmuqmwtN6Ch/transfers

**Comment by janmichek** [comment]
Looks fixed now, thanks. You can close it
