### ISSUE TITLE
Luck of info in /aex9/transfers endpoints

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/ae_mdw#198]
`/aex9/transfers` endpoint should return atleast 
- `contract id` for each transaction
- time

**Comment by kenodressel** [comment]
This is what it currently looks like:
```
  {
    "amount": 100000000000000000,
    "call_txi": 19973419,
    "log_idx": 0,
    "recipient": "ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy",
    "sender": "ak_2UGL6qArnbWx9fEkJyszssMkCjpu3VeLFBPA6MXYV3APfDSz1k"
  },
```
In order to process this information there should be at least the token contract listed too. Optionally more information about the transaction would be nice to have.
