### ISSUE TITLE
txs/backward?account does not return the contract call where you are receiver

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/ae_mdw#199]
https://testnet.aeternity.io/mdw/txs/backward?type=contract_call&limit=100&page=1&contract=ct_T6MWNrowGVC9dyTDksCBrCCSaeK3hzBMMY5hhMKwvwr8wJvM8&account=ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy
contain only contacrt_calls where `ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy` the caller

https://testnet.aeternity.io/mdw/aex9/transfers/to/ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy
in this list of tokens related transactions, we may see transaction `19973385` (tokens was send TO ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy)
https://testnet.aeternity.io/mdw/txi/19973385

**Comment by thepiwo** [comment]
@CedrikNikita the `/mdw/txs/backward?account` endpoint justs lists all native transactions for the respective account, for AEX-9 this means a contract call is just listed there from the sender, the receiver is not know natively as its part of AEX-9 specification.

These transactions are all listed in the `/aex9/transfers` endpoint that specifically parse AEX-9.

**Comment by CedrikNikita** [comment]
In order to get the full transaction list now i have to make several requests:
- for the native transactions
  - `/mdw/txs/backward?account` (returning chunks)
- for the tokens
  - `/aex9/transfers` (that returns the whole list of transaction without chunking)
    - request for each transaction in that list /txi/ (because there are no tx object)
After that i have to manually/weirdly merge this into one list in order to fulfill the pagination.

**Comment by thepiwo** [comment]
if you consider an AEX-9 transfer to an account a transaction of this account, yes. Same would need to be done for all other possible contracts that affect multiple accounts.
