### ISSUE TITLE
support for names, pointers, auctions, bids

### ISSUE THREAD

**Issue by skkw** [aeternity/ae_mdw#2]
We need several mappings and logic how to maintain the information there correct:

* active auctions (supporting sort by name, max bid, expiration height)
* plain name -> name hash 
* name pointers -> plain name 
* account -> name auction bids 
* plain name -> bids

**Comment by marc0olo** [comment]
waiting for that one =)

**Comment by marc0olo** [comment]
please make sure I (if possible) to cover the scenario mentioned here: https://github.com/aeternity/ae_mdw/issues/24#issuecomment-639497603

**Comment by skkw** [comment]
Expanding this ticket to describe the needed work.

Work so far in this area resulted in functional prototype, majority from this work will be used in another iteration, especially:
- gaining knowledge how NS work in AE node
- designing API endpoints
- some part of codebase related to syncing, formatting  

However, the result now isn't in final shape, and some design decisions need to be changed:
- simulating the NS state machine of whole history with ability to reset the simulation to any point in the past (in case fork happens) yields very complex code, which would be hard to maintain and ensure correctness
- syncing with names takes ~7 hours instead of 2.5 which it took without 

New design:
- instead of separate state machine, we will reuse NS merkle trees 
- we will diff merkle trees between generations to detect change

The huge problem of making invalidations correct in case of fork should be significantly reduced.
There is a good change to gain faster syncing.

I'll need to prototype a bit to expand this design with more detail.

**Comment by skkw** [comment]
Fixed in new version.
