### ISSUE TITLE
index Chain.create and Chain.clone events

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#208]

**Comment by mradkov** [comment]
Do we have any specs on this?

**Comment by marc0olo** [comment]
I think this had to be excluded specifically because there was a bug in the sophia compiler which got quickly fixed:
- https://github.com/aeternity/aesophia/compare/v6.0.0...v6.0.1

not sure what needs to be done here. I guess @wj2016 knows what to do :-)

**Comment by thepiwo** [comment]
Currently those created or cloned contract events are not exposed by mdw, so this should probably be done in some format.
Additionally those created or cloned contracts won't be indexed as contracts as they are not created with a ContractCreateTx, so they should be indexed.

**Comment by sborrazas** [comment]
@thepiwo yes
