### ISSUE TITLE
sync AEX-9 transactions instantly

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#211]

**Comment by thepiwo** [comment]
relates to #749, should we close one or the other @sborrazas @jyeshe ?

**Comment by jyeshe** [comment]
> relates to #749, should we close one or the other @sborrazas @jyeshe ?

If a best effort approach with a single machine is not considered enough, I would leave it separate because depending on the size of the queue and frequency of updates, in order to get faster results it might be needed to have some cluster dedicated to dry-running.

**Comment by thepiwo** [comment]
so I'll close this in favour of the other task, if we come up with a new approach we can still make a new issue
