### ISSUE TITLE
Wrong microblock returned for generation

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/ae_mdw#223]
Hey, it seems like we're returning the micro blocks for a generation in a seemingly random order.

Here is an example: https://mainnet.aeternity.io/mdw//blocks/471542-471542

The easiest example is to search for `prev_hash”:“kh`, which will be the first micro block of the generation, having the keyblock hash as his `prev_hash`. Looking closer at the other prev_hashes, you will see the same.

I smell that this is an issue of not having UIDs on microblocks, which is the reason why we can't just perform a `SORT` when returning this data from DB.

If I'm right, maybe we should make the MDW add some UID for internal use?

**Comment by jyeshe** [comment]
Currently "micro_blocks" response field is a map with the micro block hash as the key. Would this map still be needed for a certain client or may we transform it into a list (to sort it by time)? It would be possible to sort with the map but it requires a bigger change on how response is processed. 
@thepiwo @nikita-fuchs @mradkov
