### ISSUE TITLE
more SpendTx details on mdw/txs/backward?account=...

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#226]
When calling this endpoint the transactions of an account are returned.

This is a feature request to return more details for tx-type `SpendTx` if the recipient is a name id (`nm_...`). I would like to see following additional data returned in this case:
- name (`xyz.name`)
- account (`ak_...`)

**Comment by jyeshe** [comment]
@marc0olo should the account be the one from the owner of the name (recipient) or the account from the parameter?
If the first case may the recipient be an object like this?
```
recipient: {
  name: "xyz.chain",
  account: "ak_..."
}
```
when possible for the clients could become like:
```
recipient: {
  id: "nm_...",
  name: "xyz.chain",
  account: "ak_..."
}
```

**Comment by marc0olo** [comment]
Not sure if I understand the question correctly.

I think wrapping this into a separate object makes sense and should always be handled like this. But that's my personal opinion.

In most cases we would only have the account property present.

In case of having used a name_id as recipient I would expect the second example as response (of course the account there is dependent on the state at this point of time, the pointer could be changed at any time).

Maybe let's involve @thepiwo here because I assume this would be a breaking change in the API, right?

We anyway wanted to heave some versioning and cleanup of the API. So this could involve more changes for introducing a new API version.

**Comment by thepiwo** [comment]
@jyeshe @marc0olo yeah we should consider an overall versioning schema here. Maybe we can introduce a /v2/ same route endpoint with the adjusted changes?

For now as there a not that many consumer of mdw we should be fine without it, but its definitely breaking for some clients.

@jyeshe is it now implemented as proposed here? For me the PR looks non-breaking, so it should all be fine right?

**Comment by jyeshe** [comment]
Yes @thepiwo, without breaking changes. Pushed the recipient object now keeping the recipient_id outside of it.

@marc0olo @thepiwo 
Considering the pointer could change, the account returned in the new field should be the owner of name at the time of the transaction, right? Or for a particular reason should be always the last/current owner?

**Comment by marc0olo** [comment]
> @marc0olo @thepiwo
> Considering the pointer could change, the account returned in the new field should be the owner of name at the time of the transaction, right? Or for a particular reason should be always the last/current owner?

sorry, didn't have time to respond yet. so the recipient at a specific point of time is always the account-pointer (key: `account_pubkey`) of that specific AENS name. it's not about the owner of the name but about the account that pointer has been pointing when that specific tx happened. the owner of the name is completely irrelevant in that context.

**Comment by marc0olo** [comment]
@jyeshe is this handled correctly now?! just curious. haven't checked

**Comment by marc0olo** [comment]
in the description of the merged PR it says we use the owner as recipient. this is wrong!!!! cc @thepiwo

**Comment by thepiwo** [comment]
@marc0olo right, my bad not noticing in review. @jyeshe can you fix to use the account pointer of the name?

**Comment by jyeshe** [comment]
As the issue is about the recipient and it's name, the account taken was for the owner of the name (account of recipient) but no problem, we can fix that.

> account-pointer (key: account_pubkey) of that specific AENS name.

Two questions to clarify:
1) Could you provide a context of accounts involved in the transaction? From my short-sighted perspective there are only the accounts of the sender and receiver (maybe a 3rd of the owner of a contract that made the transfer). 

2) Can you explain what means this account-pointer conceptually speaking? In the model a name doesn't have it explicitly:
```
# name:
  #     index = plain_name,
  #     active = height                    #
  #     expire = height                    #
  #     claims =  [{block_index, txi}]     #
  #     updates = [{block_index, txi}]     #
  #     transfers = [{block_index, txi}]   #
  #     revoke = {block_index, txi} | nil  #
  #     auction_timeout = int              # 0 if not auctioned
  #     owner = pubkey                     #
  #     previous = m_name | nil            # previus epoch of the same name
  #
  #     (other info (pointers, owner) is from looking up last update tx)
  ```
There is a pointee that is very agregated:
```
# pointee : (updated when name_update_tx changes pointers)
  #     index = {pointer_val, {block_index, txi}, pointer_key}
```

**Comment by jyeshe** [comment]
For the second question, found something here:
https://aeternity.com/documentation-hub/protocol/node/api/naming_system_api_usage/#update
Just gonna look how to fetch it because the index is very composite.

I think I understood what it is, pls correct me if I am wrong. I can claim a name with one account but make it to point to another one, correct? That's why the owner (even considering transfers) might not be the actual recipient of the spend_tx.

**Comment by marc0olo** [comment]
> 1. Could you provide a context of accounts involved in the transaction? From my short-sighted perspective there are only the accounts of the sender and receiver (maybe a 3rd of the owner of a contract that made the transfer).

Assuming we are speaking ONLY about a `SpendTx` (which can also be an "inner-tx" in a contract call or wrapped in a GaMetaTx or PayingForTx) it's always a regular account that is the `sender` (`ak_...`). In case of the recipient it can be an account ( `ak_...`) or an AENS name_id (`nm_...`) which **at the time of the transaction** points to a specific account (`ak_...`) via pointer-key (`account_pubkey`). The owner of that AENS name is completely irrelevant for the `SpendTx`. It's just the owner of the AENS name, nothing else.

 

> 2\. Can you explain what means this account-pointer conceptually speaking? In the model a name doesn't have it explicitly:

An AENS name can have different types of pointers for all objects of the protocol (accounts, contracts, channels & oracles). The pointer-key ( `account_pubkey`) is enforced by the protocol to be used for `SpendTx`. If this pointer is not set the AENS name cannot be used for a `SpendTx`.
