### ISSUE TITLE
Querying names on new block leads to random access issues

### ISSUE THREAD

**Issue by kenodressel** [aeternity/ae_mdw#234]
Steps to reproduce:
- open https://mainnet.aeternity.io/mdw/names/active?limit=100
- wait until a new block is mined
- refresh the page
- navigate to the page listed in next
- observe `400, "random access not supported"`

---

This has been a problem in the past and might be related to the load balancer.

**Comment by kenodressel** [comment]
initial request:
![image](https://user-images.githubusercontent.com/765921/131667787-a36980b4-8e34-4529-850c-85f7cf098248.png)
followup:
![image](https://user-images.githubusercontent.com/765921/131667827-630ea43f-b12f-4c08-8112-d44eb0cd2659.png)

**Comment by thepiwo** [comment]
@venimus can you provide some feedback here?

**Comment by venimus** [comment]
Cloudfront is proxying the user trough random IP and this changes the IP-hash that is used from load balancer, I'm working on a workaround

**Comment by venimus** [comment]
It should be fixed now
