### ISSUE TITLE
mdw incompatibility with node 6.3.0

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#275]
using mdw with node 6.3.0 seems to fail when using the status endpoint

![image](https://user-images.githubusercontent.com/6539235/136170594-73f5f2db-2b03-4729-910f-df3964d695a3.png)

**Comment by jyeshe** [comment]
Syncing from 497396 to 497397 went fine. What would be your `localhost:4000/status` and Mdw commit pls?

**Comment by thepiwo** [comment]
sync seems to work, but access to the /status endpoint fails
