### ISSUE TITLE
some aex9 contract dry run might take a long time

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#295]
It happens with the `ct_BwJcRRa7jTAvkpzc2D16tJzHMGCJurtJMUBtyyfGi2QjPuMVv` on `DBN.aex9_balances(contract_pk)` for about a minute or so.

**Comment by jyeshe** [comment]
Similar ct_M9yohHgcLjhpp1Z8SaA1UTmRMQzR4FWjJHajGga8KBoZTEPwC...

**Comment by thepiwo** [comment]
@jyeshe this can be closed now with the async task adjustments, right?

**Comment by jyeshe** [comment]
The solution we've discussed now in the meeting is to cache/persist the result when updating aex9 presence.

**Comment by jyeshe** [comment]
In order to avoid heavy loads for very specific cases, the endpoint will check always the result from database table (if does not exist yet returns a 404).
