### ISSUE TITLE
investigate number of transactions in different deployments

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#329]

**Comment by jyeshe** [comment]
More transactions indexed as detected by:
https://github.com/aeternity/ae_mdw/pull/353

**Comment by jyeshe** [comment]
An example of the reason for closing:
https://mainnet.aeternity.art/mdw/txi/27158031
https://mainnet.aeternity.io/mdw/tx/th_2iRCmwPgNY1j3dwBqMHLiBgtS6HprCMY1b8GsR8T6o2QzZJGCn
https://mainnet.aeternity.io/mdw/txs/gen/503924-503926?limit=1000&page=1&recipient_id=ak_wTPFpksUJFjjntonTvwK4LJvDw11DPma7kZBneKbumb8yPeFq

The Mdw is now indexing transactions that were missing before.

**Comment by jyeshe** [comment]
until this point 31 more transactions indexed
https://mainnet.aeternity.io/mdw/txi/27290779
https://mainnet.aeternity.art/mdw/txi/27290810
