### ISSUE TITLE
make pagination stateless in frontend (include `previous` and `next` URL)

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#335]

**Comment by thepiwo** [comment]
comment from @sborrazas in chat:

1. as for the explorer right now, I don't see a place right now where you would go "back" a page, for every pagination of things (txs/oracles/etc) it always starts from the beginning or from a given generation. I would try to avoid supporting features that are never going to be used anyway
2. by using mnesia as a storage we got rid of being able to paginate this is the limitation of the database. do we know why this decision was made? or they were aware of this when they did it?
3. adding a "previous" link on every paginated response would involve either to: A. change the database we're using. B. iterate through 1-100 keys from paginated resources backwards to get to the first resource of the previous page. C. add another mnesia index that we would need to maintain that would be updated for every name, oracle, inactive oracle, etc updated

it's definitely doable, either A, B or C are going to either take a lot of work or reduce the app performance

**Comment by thepiwo** [comment]
As discussed in chat this is a "won't fix" for now. If there is a convincing reason given we can discuss a workaround.

**Comment by marc0olo** [comment]
> 1. as for the explorer right now, I don't see a place right now where you would go "back" a page, for every pagination of things (txs/oracles/etc) it always starts from the beginning or from a given generation. I would try to avoid supporting features that are never going to be used anyway

this is a very bad behavior of the frontend currently IMO. I will open an issue in the frontend about various usecases in that direction that @AtanasKrondev can analyze. maybe we find good solutions to navigate through the tx-history of accounts, contracts, etc. without having a stateless pagination in place.

I can't imagine anybody likes to click "next", "next", "next", ... until someone finds the tx that he/she was looking for.

maybe we could provide date input fields to select a time range for the tx's to display. this combined with the filter of tx-type could be quite powerful 🤔
