### ISSUE TITLE
validate name transition based on node state

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#344]
In order to enforce the consistency of mdw database regarding name tables, the transitions of the name state (from pre-claim to revoke) shall rely on the `aens_state_tree` (the ADT for keeping the state of Naming System) in the Node.

These validations will serve to precisely identify any inconsistency in case the persistence layer fails for partial log commit or any other failure after an exception or interruption.

**Comment by jyeshe** [comment]
@thepiwo this is the main reason to close the issue:
https://github.com/aeternity/ae_mdw/pull/345#issuecomment-979060850

Besides this, `update` and `transfer` name transitions are performed with the input from the chain:
- update: `delta_ttl = tx_val(tx, :name_update_tx, :name_ttl)`
- transfer: `new_owner = :aens_transfer_tx.recipient_pubkey(tx)`

The `revoke` deletes a name after a `tx` from the chain.

So the only thing I see that could be done here is to add logs with node info when `Mdw` gets stuck.

Regarding auction, the `[node_auction_end](https://github.com/aeternity/ae_mdw/blob/2d0d63abd6924dc87a24a995fd5bf6248381a460/lib/ae_mdw/db/name.ex#L251)` function from the draft wouldn't be needed because the `Mdw` already uses a chain function to calculate the start and end of an auction:
https://github.com/aeternity/ae_mdw/blob/045ee3518e38b4cdff92f7163da6f697c905b7d2/lib/ae_mdw/db/sync/name.ex#L44

**Comment by thepiwo** [comment]
@jyeshe what happens for name actions inside contracts?

**Comment by jyeshe** [comment]
@thepiwo If a name tx is not created for the name action, it would be a missing feature. Otherwise, if the action becomes a name tx, it will behave the same as above.

**Comment by jyeshe** [comment]
Opened the issue: https://github.com/aeternity/ae_mdw/issues/408
