### ISSUE TITLE
Expose internal transfers from migration phases

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#347]
in migration phases 0, 1, 2 and 3 balance was added in hard forks for token migration from erc 20 on ethereum to aeternity native tokens, the token balance changes are listed in json files, maybe also exposed by the node in some way.

https://github.com/aeternity/aeternity/tree/master/data/aecore then for each hard fork the respective accounts(_uat).json

My best guess would be to index them as internal transfers

**Comment by marc0olo** [comment]
was about to ask for that, thanks @thepiwo! :)

**Comment by thepiwo** [comment]
so to summarize we need to add the accounts for both testnet (uat) and mainnet (no suffix).

from 
https://github.com/aeternity/aeternity/tree/master/data/aecore/.genesis
https://github.com/aeternity/aeternity/tree/master/data/aecore/.minerva
https://github.com/aeternity/aeternity/tree/master/data/aecore/.fortuna

for
https://github.com/aeternity/aeternity/tree/master/data/aecore/.lima
as well the balance from `extra_accounts` and the `contracts` amount for the account of that contract (replace ct_ with ak_)

at the respective heights
https://github.com/aeternity/aeternity/blob/2b193881c42d86ed3ad360bae264cd8e0defa003/apps/aecore/src/aec_hard_forks.erl#L98-L111
