### ISSUE TITLE
add ttl to last_bid.tx in names

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#354]
localhost:
```
{
      "active": false,
      "auction": {
        "auction_end": 530136,
        "bids": [
          27968051
        ],
        "last_bid": {
          "block_hash": "mh_bof6T7dxEuRQoeY9zCmX9CvxSrAinftqQ7cWUtV87Kc7e5wT4",
          "block_height": 515256,
          "hash": "th_2pre6qbBF1aFjnfoe6A5VrfQadPcBeVdY76obzYeQnGwkfxeQT",
          "micro_index": 2,
          "micro_time": 1636820688836,
          "signatures": [
            "sg_677AxnqB8HwwXmUfzrZMUECBtNF7JZMkasw2SEfg2eJtu4n3Zp94TXZ29ZPR2r9MiK5dPCz7ZwteFjNqZwz9boiuMH9r8"
          ],
          "tx": {
            "account_id": "ak_XtJGJrJuvxduT1HFMye4PuEkfUnU9L5rUE5CQ2F9MkqYQVr3f",
            "fee": 16580000000000,
            "name": "Money.chain",
            "name_fee": 83204000000000000000,
            "name_id": "nm_2r4yxFwEpwErriXzC4bQ5Y7krC9SurwHchqfQSFXE4HvZEBEyv",
            "name_salt": 6425855109544945,
            "nonce": 1358,
            "type": "NameClaimTx",
            "version": 2
          },
          "tx_index": 27968051
        }
      },
```
[mainnet:](https://mainnet.aeternity.io/mdw/names/inactive)
```
    {
      "active": false,
      "auction": {
        "auction_end": 530136,
        "bids": [
          27968013
        ],
        "last_bid": {
          "block_hash": "mh_bof6T7dxEuRQoeY9zCmX9CvxSrAinftqQ7cWUtV87Kc7e5wT4",
          "block_height": 515256,
          "hash": "th_2pre6qbBF1aFjnfoe6A5VrfQadPcBeVdY76obzYeQnGwkfxeQT",
          "micro_index": 2,
          "micro_time": 1636820688836,
          "signatures": [
            "sg_677AxnqB8HwwXmUfzrZMUECBtNF7JZMkasw2SEfg2eJtu4n3Zp94TXZ29ZPR2r9MiK5dPCz7ZwteFjNqZwz9boiuMH9r8"
          ],
          "tx": {
            "account_id": "ak_XtJGJrJuvxduT1HFMye4PuEkfUnU9L5rUE5CQ2F9MkqYQVr3f",
            "fee": 16580000000000,
            "name": "Money.chain",
            "name_fee": 83204000000000000000,
            "name_id": "nm_2r4yxFwEpwErriXzC4bQ5Y7krC9SurwHchqfQSFXE4HvZEBEyv",
            "name_salt": 6425855109544945,
            "nonce": 1358,
            "ttl": 0,
            "type": "NameClaimTx"
          },
          "tx_index": 27968013
        }
      },
```

**Comment by jyeshe** [comment]
Not present in name paths in README.md (except for `claims.tx` not in `last_bid.tx`) but mainnet.aeternity.io returns it.

**Comment by jyeshe** [comment]
@thepiwo, ttl is not part of the tx and a name in auction (for the `last_bid.tx` in question) doesn't have also a ttl. It's only calculated and set when the auction expires. 

The field is not in the readme, it appears in mainnet.aeternity.io but with `ttl: 0` as in the description of the issue.
For these reasons this might be a won't fix (don't add the ttl to the tx).

**Comment by thepiwo** [comment]
do we expose the ttls somewhere else? Even if its only a calculated field it will be important to consumers of our api to know.

Also your input is valued here @marc0olo

**Comment by jyeshe** [comment]
One additional info: it's calculated in the future, when the auction expires. But if the governance doesn't change the info will be correct: `expire = height + :aec_governance.name_claim_max_expiration(proto_vsn(height))`

**Comment by marc0olo** [comment]
aren't we misinterpreting `ttl` here?

are we talking about the `ttl` of the transaction itself or are we talking about the `ttl` of the name?

**Comment by jyeshe** [comment]
Currently the `ttl` of the name is shown in the `info.expire_height` for active names (or inactive that had an auction expired, i.e name that was once active).

There is `info.auction_timeout` for the `ttl` of the auction (associated with name_claim_tx).

**Comment by marc0olo** [comment]
I need to take some time to think about this. not sure when I will be able to comment again. I am too far away right now from this topic unfortunately

**Comment by jyeshe** [comment]
The PR adds the ttl as the future name ttl after it's activation.
For names that were never actived (that are only in auction), this brings new information as it won't be redundant neither with info.expire_height nor info.auction_timeout.
