### ISSUE TITLE
index `:contract_create_tx` events

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#377]
Currently the events are logged only for contract calls transactions:
https://github.com/aeternity/ae_mdw/blob/ee3465822fecf346acc564e36f9e209faf8444f8/lib/ae_mdw/db/sync/transaction.ex#L82

**Comment by jyeshe** [comment]
@thepiwo events can also be emitted when calling a contract from a channel, right? if so any particular extra info should be added to these events (or to the contract, for instance if it was created from a channel)?

**Comment by thepiwo** [comment]
channel transactions are private and thus won't be indexed by mdw
