### ISSUE TITLE
oracle cannot be found

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#380]
it seems like an oracle registered via contract cannot be found when calling https://mainnet.aeternity.io/mdw/oracle/ok_a5VPJHHhiKLjRZWmuSUE9W8jSrd92T7G3F6qEEf4dC7YmGYvs

```json
{"error":"not found: ok_a5VPJHHhiKLjRZWmuSUE9W8jSrd92T7G3F6qEEf4dC7YmGYvs"}
```

the oracle has definitely existed as it responded in this transaction:
- https://mainnet.aeternity.io/mdw/contracts/calls/txi/27294255

when I am informed correctly this endpoint should provide a result for active as well as inactive (expired) oracles

**Comment by thepiwo** [comment]
also not found here: https://mainnet.test.aeternity.art/mdw/oracle/ok_a5VPJHHhiKLjRZWmuSUE9W8jSrd92T7G3F6qEEf4dC7YmGYvs

**Comment by sborrazas** [comment]
This happens because we're not indexing oracles created through contract calls. I'll have a PR up soon

**Comment by thepiwo** [comment]
@sborrazas can this be closed?
