### ISSUE TITLE
Mnesia transaction code removal

### ISSUE THREAD

**Issue by sborrazas** [aeternity/ae_mdw#387]
Right now the mnesia transaction deals with logic that can be moved outside of it for efficiency. In particular, we should be able to remove most of the calls that are made to the core modules, which potentially create exceptions that would interfere with mnesia's transaction.

Ideally, the code inside the mnesia transaction should only be a sequence of writes.

**Comment by jyeshe** [comment]
We have been working on it divided into 2 fronts (at least):
i) mutations
ii) preloading the data needed for the mutations

The #366 is a WIP for the preloading.

**Comment by jyeshe** [comment]
I wouldn't consider this an enhancement since it's an issue that affects the commit of the transaction.
