### ISSUE TITLE
Syncing process failure recovery

### ISSUE THREAD

**Issue by sborrazas** [aeternity/ae_mdw#388]
Right now, for every exception thrown in the syncing process, the middleware completely stops syncing. Most of these exceptions are gone when retrying, so we should look into mechanisms to do so without having to manually restart the server.

We should also try to implement as much of #387 as possible, so that we reduce the amount of exceptions that happen inside the mnesia transaction.

**Comment by jyeshe** [comment]
Leaving the #387 with it's own scope, this is in progress with a refactoring of the sync pipeline.

**Comment by jyeshe** [comment]
Leaving the #387 with it's own scope, this is in progress with a refactoring of the sync pipeline so that when sync process ends with a reason other than `:normal` doesn't put the subscriber down and reprocessing the height makes the sync to continue from last synced (until max_height).

**Comment by jyeshe** [comment]
Sync is not waiting for the migrations:
```
2022-03-14 11:34:02.642 [info] syncing block index at 340000
2022-03-14 11:34:09.258 [info] Indexed 144799 records in 80s
2022-03-14 11:34:09.272 [info] applied version 20220223222120
2022-03-14 11:34:09.290 [debug] tell_controllers(:app_running, :ae_mdw, :aeternity@localhost)
2022-03-14 11:34:15.220 [info] syncing block index at 330000
```
