### ISSUE TITLE
index ga_attach_tx contracts

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#397]
see https://github.com/aeternity/mdw-frontend/issues/135

**Comment by jyeshe** [comment]
Regression failed (side effect of other feature/fix):
https://testnet.aeternity.io/mdw/txs/forward?type=ga_attach&owner_id=ak_2RUVa9bvHUD8wYSrvixRjy9LonA9L29wRvwDfQ4y37ysMKjgdQ
https://testnet.aeternity.io/mdw/txs/forward?contract_id=ct_Be5LcGEN2SgZh2kSvf3LqZuawN94kn77iNy5off5UfgzbiNv4

**Comment by marc0olo** [comment]
@jyeshe are you sure this is solved? seems like we still have the problem in `v1.7.3` on testnet:

- https://explorer.testnet.aeternity.io/account/ak_23J54nHLucRppnKd4ZrnTJ4ZmF2wDUWfCHum6c7KgQWkFybPsb
- https://explorer.testnet.aeternity.io/contracts/transactions/ct_DQ8hzApwEt7d8JKQuXwKVbCLu9jp2pH2865VGoGU664c8ax4p

cc @janmichek

**Comment by jyeshe** [comment]
> @jyeshe are you sure this is solved? seems like we still have the problem in `v1.7.3` on testnet:
> 
>     * https://explorer.testnet.aeternity.io/account/ak_23J54nHLucRppnKd4ZrnTJ4ZmF2wDUWfCHum6c7KgQWkFybPsb
> 
>     * https://explorer.testnet.aeternity.io/contracts/transactions/ct_DQ8hzApwEt7d8JKQuXwKVbCLu9jp2pH2865VGoGU664c8ax4p
> 
> 
> cc @janmichek

The solution was prior to child contracts support. We will need a matrix with all possibilities and a test case for each one of them.

**Comment by marc0olo** [comment]
this is definitely an important topic as we're working on the GA MultiSig. can we prioritize that?

**Comment by jyeshe** [comment]
An example of the feature implemented:
https://mainnet.aeternity.io/mdw/txs/forward?contract=ct_Be5LcGEN2SgZh2kSvf3LqZuawN94kn77iNy5off5UfgzbiNv4
Returns a tx with type `GAAttachTx`

**Comment by jyeshe** [comment]
Also working on testnet for the 

> @jyeshe are you sure this is solved? seems like we still have the problem in `v1.7.3` on testnet:
> 
>     * https://explorer.testnet.aeternity.io/account/ak_23J54nHLucRppnKd4ZrnTJ4ZmF2wDUWfCHum6c7KgQWkFybPsb
> 
>     * https://explorer.testnet.aeternity.io/contracts/transactions/ct_DQ8hzApwEt7d8JKQuXwKVbCLu9jp2pH2865VGoGU664c8ax4p
> 
> 
> cc @janmichek

Working on Mdw side:
https://testnet.aeternity.io/mdw/txs/forward?contract=ct_DQ8hzApwEt7d8JKQuXwKVbCLu9jp2pH2865VGoGU664c8ax4p

**Comment by janmichek** [comment]
Hi, just attaching one of the links, where it should suppose to work.
https://explorer.testnet.aeternity.io/account/ak_23J54nHLucRppnKd4ZrnTJ4ZmF2wDUWfCHum6c7KgQWkFybPsb
![obrazek](https://user-images.githubusercontent.com/15363559/163371812-edba4610-39eb-44d8-b7d8-175fdd19f191.png)

**Comment by jyeshe** [comment]
@janmichek @marc0olo passing the account also works:
https://testnet.aeternity.io/mdw/txs/forward?account=ak_23J54nHLucRppnKd4ZrnTJ4ZmF2wDUWfCHum6c7KgQWkFybPsb

**Comment by jyeshe** [comment]
Closing as both endpoints works on mdw:
https://testnet.aeternity.io/mdw/txs/forward?account=ak_23J54nHLucRppnKd4ZrnTJ4ZmF2wDUWfCHum6c7KgQWkFybPsb
https://testnet.aeternity.io/mdw/txs/forward?contract=ct_DQ8hzApwEt7d8JKQuXwKVbCLu9jp2pH2865VGoGU664c8ax4p
