### ISSUE TITLE
Could not get the balance list

### ISSUE THREAD

**Issue by Lfh2msn** [aeternity/ae_mdw#415]
Could not get the account balance list under the contract address
eg:
[https://mainnet.aeternity.io/mdw/aex9/balances/ct_uGk1rkSdccPKXLzS259vdrJGTWAY9sfgVYspv6QYomxvWZWBM](https://mainnet.aeternity.io/mdw/aex9/balances/ct_uGk1rkSdccPKXLzS259vdrJGTWAY9sfgVYspv6QYomxvWZWBM)

**Comment by thepiwo** [comment]
this is an issue with the old deployment and is already fixed with the upcoming release

**Comment by jyeshe** [comment]
Complementing the reason aforementioned, it was fixed with #267

**Comment by jyeshe** [comment]
Closing after testing on mainnet deployment (took about 20 seconds because it's a big contract but #295 will address the performance).
