### ISSUE TITLE
Account list AEX9 Name obtained

### ISSUE THREAD

**Issue by Lfh2msn** [aeternity/ae_mdw#416]
Getting AEX9 account list does not know the token name directly

https://mainnet.aeternity.io/mdw/aex9/balances/account/ak_2kxt6D65giv4yNt4oa44SjW4jEXfoHMviPFvAreSEXvz25Q3QQ

**Comment by thepiwo** [comment]
@sborrazas @jyeshe will this be simple to add?

**Comment by jyeshe** [comment]
Currently the model doesn't have all the info because the AEX9 presence might be associated with a `call_txi` but it won't be complex to reindex having always the `create_txi`.

**Comment by Lfh2msn** [comment]
I think this is very important, and applications need it. It should not be processed twice at all application layers.
