### ISSUE TITLE
consider paginating mdw/aex9/balances

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#420]
result may take very long, e.g. https://mainnet.aeternity.art/mdw/aex9/balances/ct_uGk1rkSdccPKXLzS259vdrJGTWAY9sfgVYspv6QYomxvWZWBM

**Comment by thepiwo** [comment]
@sborrazas @jyeshe what do you think?

**Comment by thepiwo** [comment]
as this would be a breaking change, maybe we can then also create a branch for changes to wait for a 2.x release

**Comment by sborrazas** [comment]
@thepiwo not pagination an unlimited list of results is very dangerous. They end up being susceptible to very naive DDoS attacks, so they are a security concern

**Comment by jyeshe** [comment]
Assigning to myself as we've talked in the meeting to cache the results of long dry runs (persisting them).

**Comment by jyeshe** [comment]
Linking this to the #295 which I will assign to myself as we've talked in the meeting to cache the results of long dry runs (persisting them). The pagination could be indeed implemented regardless of the cache though to help seeing result for big contracts and be better prepare for DEX.
