### ISSUE TITLE
`/totalstats` and `/stats` broken

### ISSUE THREAD

**Issue by marc0olo** [aeternity/ae_mdw#450]
affected version: `v1.4.0`

## current response
```json
{"data":[{"height":542490,"sum_block_reward":0,"sum_dev_reward":0,"total_token_supply":243746023899258298727537613},{"height":542489,"sum_block_reward":0,"sum_dev_reward":0,"total_token_supply":243746023899258298727537613},{"height":542488,"sum_block_reward":0,"sum_dev_reward":0,"total_token_supply":243746023899258298727537613},{"height":542487,"sum_block_reward":0,"sum_dev_reward":0,"total_token_supply":243746023899258298727537613},{"height":542486,"sum_block_reward":0,"sum_dev_reward":0,"total_token_supply":243746023899258298727537613},{"height":542485,"sum_block_reward":0,"sum_dev_reward":0,"total_token_supply":243746023899258298727537613},{"height":542484,"sum_block_reward":0,"sum_dev_reward":0,"total_token_supply":243746023899258298727537613},{"height":542483,"sum_block_reward":0,"sum_dev_reward":0,"total_token_supply":243746023899258298727537613},{"height":542482,"sum_block_reward":0,"sum_dev_reward":0,"total_token_supply":243746023899258298727537613},{"height":542481,"sum_block_reward":0,"sum_dev_reward":0,"total_token_supply":243746023899258298727537613}],"next":"/totalstats?cursor=542480&limit=10"}
```

## problem:
- values are zero and total supply doesn't seem to change

----------

additionally I am wondering if there was a breaking change in `/stats` because the https://aenalytics.org webseite doesn't display the number of auctions, names, contracts & oracles anymore

**Comment by marc0olo** [comment]
update: problem is also existent for `/stats`

**Comment by jyeshe** [comment]
`mnesia_rocksdb` bug affects `/totalstats`:
```
iex(aeternity@localhost)1> :mnesia.table_info(Model.ActiveName, :size) 
0
iex(aeternity@localhost)2> :mnesia.dirty_first(Model.ActiveName)
"0.chain"
```

**Comment by marc0olo** [comment]
seems to be fixed for `/totalstats` in `v1.5.0`

still missing data for `/stats`

**Comment by marc0olo** [comment]
apparently we had a different interpretation of that endpoint and somehow we introduced breaking changes here lately.

as discussed in chat we will proably leave `/stats` like is (stats exclusively for a specific cursor/height) and add the "old stats" to the `/totalstats` endpoint.

waiting for @thepiwo to comment / confirm.

**Comment by thepiwo** [comment]
`/stats` is per height stats, e.g. for graphs
`/totalstats` is aggregated data since genesis

**Comment by marc0olo** [comment]
alright, then let's add the missing aggregated data since genesis in `/totalstats`
