### ISSUE TITLE
`/mdw/` is not defined in testnet swagger file

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#503]
I'm using https://testnet.aeternity.io/mdw/swagger/swagger.json to generate a swagger client using `swagger-client` package in JS.

The swagger file doesn't define `/mdw/` sub patch anyhow (expected to be in `basePath` property), so `swagger-client` requests https://testnet.aeternity.io/status instead of https://testnet.aeternity.io/mdw/status.

Also #160 is still actual

**Comment by marc0olo** [comment]
I don't think the swagger.json is currently a reliable source. we probably can't and shouldn't use it at the moment. this is probably also the reason why #189 exists

@thepiwo do we already have a task for the swagger definitions?

not sure if we currently have somebody who could tackle this. but at least @ifaouibadi told me he'd be interested. though I think we need him in other areas at least short term.

**Comment by davidyuk** [comment]
> we probably can't and shouldn't use it at the moment

I'm using it with some fixes in Base app, would be more difficult to don't use it

**Comment by thepiwo** [comment]
closing in favour of general swagger improvements issue
