### ISSUE TITLE
Replace names/pointees with name/pointees in Swagger file

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#508]
The endpoint https://mainnet.aeternity.io/mdw/name/pointees/ak_jupBUgZNbcC4krDLR3tAkw1iBZoBbkNeShAq4atBtpFWmz36r have a wrong definition in Swagger file:
```
    "/names/pointees/{id}": {
      "get": {
        "deprecated": false,
        "description": "Get names pointing to a particular pubkey.",
        "operationId": "get_pointees_by_id",
        ...
```

**Comment by thepiwo** [comment]
closing in favour of general swagger improvements issue
