### ISSUE TITLE
Different auction schema depending on if name was registered before

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#509]
https://mainnet.aeternity.io/mdw/name/tel.chain

```json
{
  "active": false,
  "info": {
    "auction_end": 576662,
    "bids": [...],
    "last_bid": { ... }
  },
  "name": "tel.chain",
  "previous": [],
  "status": "auction"
}
```

https://mainnet.aeternity.io/mdw/name/btc.chain

```json
{
  "active": false,
  "auction": {
    "auction_end": 559686,
    "bids": [...],
    "last_bid": {...}
  },
  "hash": "nm_REqqEHnPPD5ZGgqeHSn9HwE5K1e99kmE4pjsKJSJbjoH8ZMdA",
  "info": {
    "active_from": 330811,
    "auction_timeout": null,
    "claims": [
      14691010,
      12444043
    ],
    "expire_height": 481366,
    ...
  },
  "name": "btc.chain",
  "previous": [
    {
      "active_from": 192815,
      "auction_timeout": null,
      "claims": [
        4813782,
        4726470
      ],
      "expire_height": 242815,
      ...
    }
  ],
  "status": "auction"
}
```

So, in the first case would be nice to have name hash, and `info` renamed to `auction` (otherwise, I should do `(response.auction ?? response.info).auction_end` on client side). Can't confirm that the current behavior is defined in the Swagger file.

**Comment by thepiwo** [comment]
closing in favour of general swagger improvements issue

**Comment by thepiwo** [comment]
@jyeshe @sborrazas reopened this, maybe we can check if this is actually resolved?

**Comment by jyeshe** [comment]
![image](https://user-images.githubusercontent.com/44991200/176967192-75b0d054-bd0d-4f1f-9b1b-5301bbfe16ba.png)
the `hash` was added and the `info` prevailed (`/v2/names/{plain_name}` returns `auction` information under `info` when `status` is `"auction"`) swagger v2 is consistent, it has only an "info" property.

**Comment by thepiwo** [comment]
@jyeshe @davidyuk so this can be closed?

**Comment by jyeshe** [comment]
Hey @davidyuk I think it was fixed under `info` in order to use the same field when the name becomes `active` or `inactive` (without auction). Is this good for you otherwise we might analyze another way on a /v3?

**Comment by davidyuk** [comment]
> so this can be closed?

Looks so

**Comment by sborrazas** [comment]
@nikita-fuchs you can use the v3 endpoint where's there's an "auction" property if the name is in auction, and null if not. This avoid using unnecessary nesting and non-descriptive names like "info" 

https://testnet.aeternity.io/mdw/v3/names/testname0001.chain

**Comment by CedrikNikita** [comment]
Are v3 endpoints stable enough to start using them in production?
