### ISSUE TITLE
Testnet node is unsynced 🤷‍♀️ 

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#510]
```
$ curl https://testnet.aeternity.io/mdw/status | jq .
{
  "mdw_async_tasks": {
    "long_tasks": 0,
    "producer_buffer": 0,
    "total_pending": 0
  },
  "mdw_height": 552434,
  "mdw_synced": false,
  "mdw_syncing": false,
  "mdw_tx_index": 25728638,
  "mdw_version": "1.4.0",
  "node_height": 555885,
  "node_progress": 100,
  "node_revision": "839148bafa678d7dda203245aff73c0236bf8efe",
  "node_syncing": false,
  "node_version": "6.3.0"
}
```
the sync gap is about 3000 blocks

**Comment by jyeshe** [comment]
Hi @davidyuk this Mdw version 1.4.0 is still in the old version which is not able to cope with some of contracts (when it's code is a reference to the code of another contract for instance) so it hangs.

I am closing this issue in favor of:
https://github.com/aeternity/ae_mdw/issues/513

Thanks
