### ISSUE TITLE
automatically publish docker image

### ISSUE THREAD

**Issue by davidyuk** [aeternity/ae_mdw#516]
I've checked https://hub.docker.com/u/aeternity, but can find the only old middleware.

**Comment by marc0olo** [comment]
we don't have a good solution for this yet. was also a topic I raised multiple times already.

see #195 and #334 

personally I created a repository to build and publish a node image along with mdw. but it will never include devmode.

see https://github.com/kryptokrauts/ae-image-builder

it is being published here: https://hub.docker.com/r/kryptokrauts/aeternity/tags

**Comment by thepiwo** [comment]
@venimus do you have an update on this?

**Comment by marc0olo** [comment]
@venimus you recently said we can now publish a docker image, right? is this published already? is the process automated?

**Comment by thepiwo** [comment]
for tags and master branch (maybe even better release-branches, with rc tag)

**Comment by thepiwo** [comment]
@venimus is there any update on this?

**Comment by thepiwo** [comment]
@venimus is there any update on this?

**Comment by mmpetarpeshev** [comment]
I'm not aware of that project /repo. I will need more context to able to help with something.

**Comment by thepiwo** [comment]
mostly we are trying to get awareness from @venimus

**Comment by venimus** [comment]
I think that is finally resolved in #1123
