### ISSUE TITLE
negative active names stats

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#557]
```
{
  "data": [
    {
      "active_auctions": 0,
      "active_names": -5,
      "active_oracles": 0,
      "block_reward": 259282498430340000000,
      "contracts": 0,
      "dev_reward": 31719183309660000000,
      "height": 132761,
      "inactive_names": 5,
      "inactive_oracles": 0
    },
```

**Comment by marc0olo** [comment]
@jyeshe why is this an issue? as far as I understood this is a delta stats endpoint now.

we should consider renaming the property. but from my interpretation this means that 5 names expired on that height. is that correct?

**Comment by jyeshe** [comment]
exactly @marc0olo , I think we could change the names in /v2 and bring new values like names_inactivated/names_expired and names_activated, or something similar to differentiate the transitions.

**Comment by marc0olo** [comment]
> exactly @marc0olo , I think we could change the names in /v2 and bring new values like names_inactivated/names_expired and names_activated, or something similar to differentiate the transitions.

agree they should be more meaningful. the current naming reflects global stats which aren't served over this endpoint anymore.

maybe we should even rename the endpoint to `delta-stats` or `deltastats` in `v2`. for the naming of the attributes I propose:
- `names_activated`
- `auctions_started`
- `oracles_registered`
- `names_expired`
- `oracles_expired`
- `contracts_created`

for `/v1` I don't know - this was already a breaking change for users that tried to fetch the stats back then interpreting it as global statistic.

but I would definitely do the fix you mentioned to show only the amount of activated names in `active_names` as we have the number of expired names in `inactive_names` as it seems. but still it can be confusing right now.

**Comment by jyeshe** [comment]
Both suggestions were accepted @marc0olo , I am going to work on it.
