### ISSUE TITLE
Needed data for a correct UI visualization

### ISSUE THREAD

**Issue by stanislav-slavov** [aeternity/ae_mdw#56]
**Oracles:**

- A way to retrieve all active Oracles

- expiration_date field is required data for the end user

- 
<img width="972" alt="Screenshot 2020-08-06 at 15 59 17" src="https://user-images.githubusercontent.com/7085525/89534641-f11b0900-d7fd-11ea-8261-9b268602b8ec.png">

In order to display query and response data for a specific query_id we have to combine oracle_query + oracle_response entities data and visualize it in a single record. In the oracle_response entity body we have query_id which points us to the needed oracle_query, but we are unable to retrieve the needed data for the specific oracle_query by its query_id.

A way to retrieve oracle_query by query_id is needed.
 
**Channels**

- A way to retrieve all active Channels

**Generations**

- Crucial data for visualizing a generation data: 
<img width="1004" alt="Screenshot 2020-08-07 at 15 27 48" src="https://user-images.githubusercontent.com/7085525/89645662-eb3b2b80-d8c2-11ea-963c-830ac5836540.png">

- generation list data:
<img width="990" alt="Screenshot 2020-08-07 at 15 28 21" src="https://user-images.githubusercontent.com/7085525/89645744-1faee780-d8c3-11ea-9620-8054ca88886b.png">

- Micro blocks data for a Key block(list of transactions)

**Comment by thepiwo** [comment]
> Micro blocks data for a Key block(list of transactions)
can be fetched from the node directly

**Comment by skkw** [comment]
This support should now be implemented.

* all active oracles - via `/oracles/active` endpoint

* expiration_date - we can't use real world dates, be we have `expiration_height` in the reply:
```
      "active": true,
      "active_from": 289544,
      "expire_height": 334544, # <------
```  
That could be used for approximation of real date...

* channels - this support wasn't implemented as per Yani's wishes... new frontend should have the link to Channels removed

* generations - implemented via `/blocks` endpoints
This endpoint is super heavy, each request can easily result in thousands of DB reads.
Lets use it as is for now, we will implement a cache over this data.

* generation list data - can be easily derived from `/blocks` endpoints - for now, later we will have specialized endpoint

* Micro blocks data for a Key block(list of transactions) - via `/txs/gen` endpoint
