### ISSUE TITLE
endpoint errors when direction scope is not passed

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#565]
https://mainnet.aeternity.io/mdw/txs 
https://mainnet.aeternity.io/mdw/txs?direction=forward&type=channel_create&limit=1 
https://mainnet.aeternity.io/mdw/v2/blocks

On the second, direction is a param so default scope is not being detected.

This task must include increased test coverage.

**Comment by sborrazas** [comment]
`v1` never had a [`/txs`](https://github.com/aeternity/ae_mdw/blob/c8e8646c85414b0b27298d937c4868f582b83dde/lib/ae_mdw_web/router.ex#L66) or [`/blocks`](https://github.com/aeternity/ae_mdw/blob/c8e8646c85414b0b27298d937c4868f582b83dde/lib/ae_mdw_web/router.ex#L54) route that didn't include the direction (`/txs/forward`) or the scope (`/txs/gen/0-100`), so I don't think this is a bug or a feature that we need to support

**Comment by jyeshe** [comment]
It was somehow in the README and caused an error on the automated requests. The [v2/blocks](https://mainnet.aeternity.io/mdw/v2/blocks) have been fixed at some point from 1.6.1 to 1.7.1 but I think supporting `/blocks` and `/txs` without scope would cause no harm (with the benefit of making the endpoint easier to use). Renamed the PR from `fix` to `feat` though.

**Comment by jyeshe** [comment]
Not an issue.
