### ISSUE TITLE
contracts/calls route not working

### ISSUE THREAD

**Issue by quantum0hound** [aeternity/ae_mdw#572]
https://mainnet.aeternity.io/mdw/contracts/calls?contract_id=ct_BX8hjuPqVcRV9fkQfbWw8JHAw9KXM1ERZRUu8CAWShCaCP7jp
returns: 
`{"data":[],"next":null}`

and logs request return valid result:
https://mainnet.aeternity.io/mdw/contracts/logs?contract_id=ct_BX8hjuPqVcRV9fkQfbWw8JHAw9KXM1ERZRUu8CAWShCaCP7jp

**Comment by jyeshe** [comment]
works for this:
https://mainnet.aeternity.io/mdw/contracts/calls?contract_id=ct_vxg1raPbxkboAdxmSMBzEczZgSXT2Vueu238MPydd9iSntN5G

**Comment by jyeshe** [comment]
`ct_BX8hjuPqVcRV9fkQfbWw8JHAw9KXM1ERZRUu8CAWShCaCP7jp` is peculiar in the sense it was compiled with 6.1.0:
https://mainnet.aeternity.io/mdw/txs/forward?type=contract_create&contract=ct_BX8hjuPqVcRV9fkQfbWw8JHAw9KXM1ERZRUu8CAWShCaCP7jp

**Comment by marc0olo** [comment]
> `ct_BX8hjuPqVcRV9fkQfbWw8JHAw9KXM1ERZRUu8CAWShCaCP7jp` is peculiar in the sense it was compiled with 6.1.0:

if it is related to the compiler version this is a serious thing as I expect all future contracts to be compiled with the latest version

**Comment by quantum0hound** [comment]
Thanks, the contract was compiled using https://studio.aepps.com/, will use txs route

**Comment by jyeshe** [comment]
@quantum0hound @marc0olo the path of the endpoint is not so clear but it returns only the internal calls as defined by:
"A running contract can call other functions during execution. These calls are recorded and can be queried later."

For calls to contract methods please continue using the `/txs` route:
https://mainnet.aeternity.io/mdw/txs/forward?type=contract_call&contract=ct_BX8hjuPqVcRV9fkQfbWw8JHAw9KXM1ERZRUu8CAWShCaCP7jp
