### ISSUE TITLE
analyse truncating cursor key to limit cursor size 

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#718]
All cursors built with variable length key should be reviewed (the default Phoenix param limit might be a reference to consider).

**Comment by jyeshe** [comment]
Analyse specially for AEX-N ... one alternative would be to truncate the name or the symbol before rendering the cursor (`next` iterator would still work)

**Comment by thepiwo** [comment]
@jyeshe is this still something we need to take care of?

**Comment by jyeshe** [comment]
> @jyeshe is this still something we need to take care of?

Maybe only regarding AENS names, @thepiwo , but not to AEX-N anymore. I remember you've mentioned a discussion regarding names that involved also the length, right? Could we leave this limit to the Node? So far couldn't create a name bigger than 70 chars which is already a considerable length for a name.

**Comment by thepiwo** [comment]
I thought we also fixed the cursor for long names (cc @sborrazas )

**Comment by jyeshe** [comment]
> I thought we also fixed the cursor for long names (cc @sborrazas )

For AENs it's pending depending on Node decision.

**Comment by thepiwo** [comment]
names have a maximum length so its not a big issue
