### ISSUE TITLE
define delay tolerance for aex9 balance update processing

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#723]
Please ignore the comment on 1.7.3, my bad. I was remembering about an old discussion on some PR to make the sync back to height bases but it was not on 1.7.3 (very likely to be on an intermediary version before release).
 
The in memory handling doesn't restore yet the prior behavior which is to be available to run during the same height (per microblock basis).

The DEX use case might be one that demands the aex9 balance to be available as soon as possible.

**Comment by jyeshe** [comment]
@thepiwo this issue depends on your prioritization and analysis because I didn't want to block the PR #676. If it should be part of the PR could you comment there please? If not I would like only to be aware of what will be decided with @sborrazas. If needed I would be glad to help with this part of the implementation for the in-memory handling.

**Comment by jyeshe** [comment]
Relates to #211

**Comment by thepiwo** [comment]
I think this can and should be changed to be instant with https://github.com/aeternity/ae_mdw/pull/676, but I'll let @sborrazas have the final word here.

**Comment by sborrazas** [comment]
Taking into account @jyeshe's edited comment, IIRC the reason for us having asynchronous tasks for indexing aex9 tokens was that executing these contract functions could potentially take too long, regardless of how long it would take to store them on the DB

So I don't think it would be straightforward to actually have aex9 tokens in real-time, but we could have some additional mechanisms and evaluate different ways where it would be doable

**Comment by jyeshe** [comment]
> Taking into account @jyeshe's edited comment, IIRC the reason for us having asynchronous tasks for indexing aex9 tokens was that executing these contract functions could potentially take too long, regardless of how long it would take to store them on the DB
> 
> So I don't think it would be straightforward to actually have aex9 tokens in real-time, but we could have some additional mechanisms and evaluate different ways where it would be doable

The starting point of this issue was just to raise a flag that if the we have a release with the PR as is, the aex9 balance update would wait always at least 10 heights to run. Let's talk when I get back.

**Comment by jyeshe** [comment]
> I think this can and should be changed to be instant with #676, but I'll let @sborrazas have the final word here.

you're welcome for the reminder (: otherwise the release would have delayed aex9 results (moving away from the instantaneous goal)

**Comment by jyeshe** [comment]
Closing as the goal is confirmed to be [sync AEX-9 transactions instantly](https://github.com/aeternity/ae_mdw/issues/211)

As it's known that the Node takes sometimes more than a minute for big contracts, the goal will be handled through best effort with 1 Mdw instance (until optimization on Node side)
