### ISSUE TITLE
Endpoint `/aex9/balances/account` returning duplicates

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/ae_mdw#735]
https://testnet.aeternity.io/mdw/aex9/balances/account/ak_2AVeRypSdS4ZosdKWW1C4avWU4eeC2Yq7oP7guBGy8jkxdYVUy
308 entities returned, only 28 of them uniq

**Comment by jyeshe** [comment]
To be solved along with https://github.com/aeternity/ae_mdw/issues/459
