### ISSUE TITLE
Add State channel stats

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#748]
- for purpose of new explorer
- count and locked value

![obrazek](https://user-images.githubusercontent.com/15363559/176406174-b50c5247-b960-476d-bbde-7df527e57928.png)

**Comment by thepiwo** [comment]
in regards to stats #124

**Comment by sborrazas** [comment]
In order to get the all the channels activity you can use the following filter of the /v2/txs endpoint:
```
curl https://mainnet.aeternity.io/mdw/v2/txs?type_group=channel
```

In order to get a list of the channels created (sorted by last) you can also filter by the specific channel create tx:
```
curl https://mainnet.aeternity.io/mdw/v2/txs?type=channel_create
```

And if you want to filter all transactions done to a specific channel you can do:
```
curl https://mainnet.aeternity.io/mdw/v2/txs?channel=ch_2CwnbjYN11rTrNCmArjHECM3GKNHECqfm6rUQt6RSaRjfTcqPm
```

@janmichek would we still need a list of all channels filtered by some value? Would we also need the total number of channels created (per generation or total)?

**Comment by sborrazas** [comment]
@janmichek those examples I sent are only if you want to know the latest activity for a specific channel or the latest channel creations. If you want to know the total open channels traversing through them wouldn't be feasable/scalable. We would need to add a new endpoint.

My question was more directed towards understanding what you would need from these new endpoints? e.g. just the number of total open channels? the number of opened channels between some given scope of generations? Also, what would be the locked value? The current AE locked value? Or the locked value per generation?

**Comment by janmichek** [comment]
I think we want to use here some global stats
`number of total open` and  `current AE locked value` 
Right? @thepiwo @marc0olo 

Later we will need similar values per channel https://github.com/aeternity/ae_mdw/issues/823

**Comment by thepiwo** [comment]
@janmichek those we would probably want "per block" so we can eventually graph them, not just the latest info

**Comment by marc0olo** [comment]
@sborrazas I would have to double check - maybe @janmichek and @thepiwo can provide more clarity. but I guess we also have a view where we wanna show a chart which shows the total value locked (AE) over time

**Comment by janmichek** [comment]
In future, we might view it per block.
But for me now, to complete the Info tiles feature I just need total stats. 
Just these two numbers would fulfill my requirements .]

 https://master-explorer.prd.aepps.com/
![obrazek](https://user-images.githubusercontent.com/15363559/183607499-203174c8-02f8-4891-91f6-94d4345c865a.png)

I suggest going step by step and to create another Issue for this, as this might block the delivery.

**Comment by sborrazas** [comment]
@janmichek this is now on production and accessible via https://mainnet.aeternity.io/mdw/v2/totalstats

**Comment by janmichek** [comment]
> ttps://mainnet.aeternity.io/mdw/v2/txs?type=channel_create

Hello, thanks for preparing the API. Here I just wanted to verify - it's not named explicitly as we have in design - so

![obrazek](https://user-images.githubusercontent.com/15363559/187457126-cad0f2a7-6cc0-409c-921f-8c9b052dd65b.png)

`On-Chain Updates` is a `Nonce`?

![obrazek](https://user-images.githubusercontent.com/15363559/187457655-13f70d0f-6931-47ed-b129-d0951c8be92a.png)

**Comment by marc0olo** [comment]
> `On-Chain Updates` is a `Nonce`?

`nonce` is the nonce used by `from_id` in this case if I am correct. irrelevant in this case.

from what I can see in the screenshot the amount of on-chain updates is missing

**Comment by sborrazas** [comment]
This issue was about exposing channels locked AE + amount of open channels, as per the requirement here https://github.com/aeternity/ae_mdw/issues/748#issuecomment-1209101734

We should move this discussion to #823 .

What we need is an endpoint exposing all of the open channels with the data shown in that table. That's what I'm working on right now

**Comment by marc0olo** [comment]
was about to comment that. thanks for clarifying @sborrazas :-)
