### ISSUE TITLE
Prepare dataset for explorer contract charts

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#758]
I think these datasets are not even defined as a task, right?
![obrazek](https://user-images.githubusercontent.com/15363559/176441092-9d22e387-ebf0-4976-9dbd-69002dc2025d.png)

Could we process this to some nice response from endpoint, please?

_Originally posted by @janmichek in https://github.com/aeternity/ae_mdw/issues/124#issuecomment-1169944701_

**Comment by thepiwo** [comment]
@janmichek @lukeromanowicz lets find out how we can help you best here, currently we expose certain stats per block, we could expose more stats within this if its helpful. A calculation from key-block to time can be done in both directions by a frontend or simplified backend (for additional filtering/performance)

**Comment by janmichek** [comment]
outdated
