### ISSUE TITLE
Consider forward pagination on alphanum AEX-N endpoints

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#770]
On `/v2` the default pagination direction is `backward`. This makes sense for most endpoints/requests as they are somehow time-related through blocks, generations or transaction index (time related responses).

However the endpoints that list AEX-N tokens mainly provide a response sorted by alphanumerical fields from `meta_info` such as `name` and `symbol`. For these requests (`/aex9` and `/aex141`), it would be more intuitive if they are sorted in ascending order by default (when using `by=name` or `by=symbol`).

Same would apply to names `endpoints`.

**Comment by thepiwo** [comment]
@jyeshe is this still open?

**Comment by jyeshe** [comment]
> @jyeshe is this still open?

Yes Phillip, it would be an enhancement for v3. Tags added, thanks!

**Comment by thepiwo** [comment]
not a breaking change right, so we could include it in v2?

**Comment by jyeshe** [comment]
> not a breaking change right, so we could include it in v2?

I would suggest on v3 because changes the behavior to be the opposite introducing a bug in the client apps. It wouldn't break unless the endpoint is monitored to check if the clients are always passing the direction.

**Comment by thepiwo** [comment]
we discussed to not change default ordering even in future versions of the api, users can always choose the direction explicitly if they wish
