### ISSUE TITLE
Calculate experation time on backend?

### ISSUE THREAD

**Issue by janmichek** [aeternity/ae_mdw#831]
Helllo! here I want to propose functionality that I think might belong to backend.
Its about displaying time values in human-readable format, not just blocks.

In order to get this value
![obrazek](https://user-images.githubusercontent.com/15363559/183615077-588b3633-a122-481c-a689-339b9e989725.png)

...i have to do daisy chaining of two async calls on frontend. For this, I think that is a good opportunity to solve it on the backend. Personally, I would hide this computational complexity behind walls of the backend.

The first call is to get names data.
The second call is basically this algorithm 
https://github.com/aeternity/mdw-frontend/blob/b02ac2615694b17a92c106c2a0d7219a6226bee0/partials/name.vue#L111
( I am taking this from old explorer, but do not mind).

**Comment by janmichek** [comment]
What u think about this? @thepiwo ?

**Comment by marc0olo** [comment]
> The second call is basically this algorithm
> https://github.com/aeternity/mdw-frontend/blob/b02ac2615694b17a92c106c2a0d7219a6226bee0/partials/name.vue#L111
> ( I am taking this from old explorer, but do not mind).

couldn't we improve that with data store? do I understand right that we currently call the node API for each row just to calculate the approximate time?

**Comment by janmichek** [comment]
> > The second call is basically this algorithm
> > https://github.com/aeternity/mdw-frontend/blob/b02ac2615694b17a92c106c2a0d7219a6226bee0/partials/name.vue#L111
> > ( I am taking this from old explorer, but do not mind).
> 
> couldn't we improve that with data store? do I understand right that we currently call the node API for each row just to calculate the approximate time?

Yes its called per every row. For this, I think Its better job to achieve this on backend

**Comment by janmichek** [comment]
Here 
https://github.com/aeternity/explorer-frontend/blob/685ecdd118b8d2dab97474480a48ac3ad3da9e6a/src/components/AuctionsPanel.vue#L89

and here 
https://github.com/aeternity/explorer-frontend/blob/685ecdd118b8d2dab97474480a48ac3ad3da9e6a/src/components/NamesPanel.vue#L83

**Comment by thepiwo** [comment]
I don't feel this belongs in the mdw as the calculation is quite simple it can be handled in frontend, if you disagree and want to discuss further, just reopen

**Comment by janmichek** [comment]
Well, this is really annoying. I have documented several solutions that need to be set on FE to ensure synchronicity.
Could be solved with some simple computation on mdw and release several paint points on FE.
https://aeternity-blockchain.atlassian.net/browse/EX-154

**Comment by janmichek** [comment]
Hello team, 
I want to reopen this issue. 

Some endpoints are sending `height`, but some returning `height` and `micro_time` (we can immediately use)
There is no logic behind what endpoints are returning. Also, I noticed that to some endpoints the attribute `micro_time` started appearing. Can we do this for all of them? 

We would like to move unnecessary computations to MDW

Namely:

`names`
`channels`
`logs`

**Comment by thepiwo** [comment]
`micro_time ` is returned wherever its part of the core protocol and consensus, its never calculated in the mdw.

**Comment by janmichek** [comment]
> `micro_time` is returned wherever its part of the core protocol and consensus, its never calculated in the mdw.

Thanks for the explanation. I was not aware of that. 


So if the path of information is
Protocol -> Middleware -> AeScan FE
I still see a better place the Middleware to append a computed value to that response. 

Would it be possible to do the computation there?

Q: how is it possible that some `micro_time` attributes suddenly appeared in some responses? 

When I reused these newly appeared time values, I discovered, It differs from FE computation. I think it's also a good ide to keep a single source of truth, other than compute it in different places.

**Comment by thepiwo** [comment]
maybe @sborrazas @jyeshe can elaborate

**Comment by sborrazas** [comment]
> > `micro_time` is returned wherever its part of the core protocol and consensus, its never calculated in the mdw.
> 
> Thanks for the explanation. I was not aware of that.
> 
> So if the path of information is Protocol -> Middleware -> AeScan FE I still see a better place the Middleware to append a computed value to that response.
> 
> Would it be possible to do the computation there?
> 
> Q: how is it possible that some `micro_time` attributes suddenly appeared in some responses?
> 
> When I reused these newly appeared time values, I discovered, It differs from FE computation. I think it's also a good ide to keep a single source of truth, other than compute it in different places.

`micro_time` is the time specified when creating the key/micro block, but it does not necessarily match reality. I would try to always use this value anyway (better than the estimate). Future values (e.g. expiration) will obviously need to be estimated, and this won't be calculated by the middleware. 

Ideally we should include `micro_time` on all endpoints that reference a micro-block, we should probably search through and figure out which ones don't have it. But for now, would you be able to list which ones you are most urgently needing?

**Comment by janmichek** [comment]
As consulted on the Galaxy event with @jyeshe , this should be doable and desired to compute on MDW. Could we reopen and process this, please?

**Comment by jyeshe** [comment]
> As consulted on the Galaxy event with @jyeshe , this should be doable and desired to compute on MDW. Could we reopen and process this, please?

I don't see an obstacle to include a field called `aprox_expiration`, that returns the expiration in minutes or hours for names except that when the Mdw is not fully synced the field would return `nil` since it would need to estimate the time diff based on height diff (from expiration to current). It can be cheaply be computed in the Mdw and would provide extra info to the users that doesn't know the estimation of 3 minutes per block height. However the case here is a client that does know (: Could you tell more details @janmichek why the current computation needs to be replaced with one made on the Mdw?

**Comment by sborrazas** [comment]
<img width="721" alt="Screen Shot 2023-05-31 at 8 07 32 AM" src="https://github.com/aeternity/ae_mdw/assets/750314/8b55c0e7-77f1-4e2b-b948-212e1355fc2e">

Posting this discussion from the public Slack channel from yesterday's morning here to keep a record of it. Creating a new issue with the feature details to follow up on implementation
