### ISSUE TITLE
Improve dry-run speed for getting AEX-9 balances

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#839]
Just a reminder for now

@jyeshe can you add some numbers, whats the worst case contract, whats number of accounts, execution speed, gas used?

**Comment by jyeshe** [comment]
> Just a reminder for now
> 
> @jyeshe can you add some numbers, whats the worst case contract, whats number of accounts, execution speed, gas used?

### Setup common for all calls:

1. Mdw and Node sync turned off.
2. Dry-running params:

```
accounts = [%{
  pub_key: <<13, 24, 60, 171, 170, 28, 99, 114, 174, 14, 112, 19, 49, 53, 233, 194, 46, 149,
               172, 14, 114, 22, 38, 51, 153, 136, 58, 149, 27, 56, 30, 105>>, 
  amount: trunc(:math.pow(10, 35))
}]
block_hash = <<135, 220, 79, 61, 155, 26, 134, 95, 158, 160, 187, 84, 18, 237, 119, 3, 51,
   143, 154, 96, 252, 46, 49, 72, 44, 254, 214, 220, 214, 43, 57, 52>>
txs =
 [
   tx: {:aetx, :contract_call_tx, :aect_call_tx, 106,
    {:contract_call_tx,
     {:id, :account,
      <<13, 24, 60, 171, 170, 28, 99, 114, 174, 14, 112, 19, 49, 53, 233, 194,
        46, 149, 172, 14, 114, 22, 38, 51, 153, 136, 58, 149, 27, 56, 30,
        105>>}, 1,
     {:id, :contract, contract_pubkey}, 3, 200000000000, 0, 0, 10000000000000000000000, 1000000000,
     <<43, 17, 128, 36, 107, 71, 63>>, [],
     <<13, 24, 60, 171, 170, 28, 99, 114, 174, 14, 112, 19, 49, 53, 233, 194,
       46, 149, 172, 14, 114, 22, 38, 51, 153, 136, 58, 149, 27, 56, 30, 105>>}}
 ]
```

### Command

`:aec_dry_run.dry_run(block_hash, accounts, txs, tx_events: false)`

### Contracts
- `ct_M9yohHgcLjhpp1Z8SaA1UTmRMQzR4FWjJHajGga8KBoZTEPwC`
  - num accounts = 45315
  - timings (microsecs)
    - 86112302
    - 84127361
    - 86411018

- `ct_BwJcRRa7jTAvkpzc2D16tJzHMGCJurtJMUBtyyfGi2QjPuMVv` 
  - num accounts = 45382
  - timings (microsecs)
    - 87231601
    - 88242721
    - 88093182

### Gas used 

Both contracts required a gas close to 910_000_000 changing the gas parameter (in the place of 10000000000000000000000 of `txs` param). For a reference, `ct_uGk1rkSdccPKXLzS259vdrJGTWAY9sfgVYspv6QYomxvWZWBM` is a contract with smaller balances (3423 accounts) and demanded 69_000_000.

**Comment by jyeshe** [comment]
All tests were performed with the Mdw processing no endpoint request.

When the dry-run is executed in parallel for both contracts it takes 15 seconds more and if the Mdw sync is turned on around 35 more from base timings.

**Comment by thepiwo** [comment]
just as a reminder, this is the issue to improve dry-running speed in particular, not concerning other optimizations

**Comment by jyeshe** [comment]
Closing with #969 as aex9 balances are fast as possible by deriving from events. 
All changes and investigations on the mdw are done. To be analysed on the Node after RocksDB refactor (without mnesia).
