### ISSUE TITLE
Expose miners info on stats endpoint

### ISSUE THREAD

**Issue by sborrazas** [aeternity/ae_mdw#844]
refs #124 

Stats we should display:
total miners - not existing, new feature issue should be created
A global stat display on the new `/v2/stat` endpoint

total reward per miner - not existing, new feature issue should be created
A new endpoint `/v2/minerstats` which will display the list of miners with the total reward of each

**Comment by thepiwo** [comment]
@sborrazas this can be closed, right?

**Comment by marc0olo** [comment]
do we have that now? didn't know that. cool!

**Comment by marc0olo** [comment]
just in regards to consistency a question as we had that topic also on explorer side:
- is the list displaying unique miners or beneficiaries?

**Comment by sborrazas** [comment]
@marc0olo it's displaying beneficiary accounts on `/v2/minerstats` because the miner account doesn't not itself receive any amount

**Comment by thepiwo** [comment]
@sborrazas closing this, feel free to reopen if we forgot anything
