### ISSUE TITLE
Sorting meta info fields for AEX-n contract validation

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#847]
## Problem

From Sophia programmer perspective, the order fields of a record wouldn't make difference on the type but for the Mdw if the `symbol` definition comes before the `name` it makes a difference because the when calling a contract it doesn't return the field names, only the values.

This affects somehow also if a contract is properly indexed or not (after identified as compliant to a standard or not) because if for example the `decimals` is defined as first field of AEX-9 meta_info record, the type of the return of `meta_info` method is changed for the Mdw by calling the Node. 

## Possible solution (on Mdw)

Accept any combination of field order and if the user swaps the order of two fields of the same type like `name` and `symbol`, it can be noticed on testnet and the user might change back to the order described in the standard to have the fields indexed with proper values.

**Comment by marc0olo** [comment]
we're also discussing the general requirement to provide source code of contracts in order to be indexed by the mdw. this would solve that problem and we'd be able to parse the fields of a `record`.

also we wouldn't have to index all the spam shit out there and encourage everybody to open source their code

**Comment by marc0olo** [comment]
also for contract verification we have to think about how this information should be provided. probably the same way like the http compiler expects it to be provided

**Comment by thepiwo** [comment]
@jyeshe @marc0olo can you update regarding the current state of this, we have agreed on a sorting and can keep this as is, right?

**Comment by jyeshe** [comment]
> @jyeshe @marc0olo can you update regarding the current state of this, we have agreed on a sorting and can keep this as is, right?

The mdw is not accepting yet any field order, only one as defined in the standard (the other possible records with same fields still invalidate the contracts).
