### ISSUE TITLE
total_pending async stat is not decremented to 0 (intermittent)

### ISSUE THREAD

**Issue by jyeshe** [aeternity/ae_mdw#869]
While there are no tasks neither on pending or processing state, the `total_pending` counter doesn't display 0 tasks. 

To be deleted from processing state it needs to execute also `Database.dirty_delete(Model.AsyncTask, task_index)` using the same `task_index`

**Comment by thepiwo** [comment]
@jyeshe can this be closed?

**Comment by jyeshe** [comment]
> @jyeshe can this be closed?

We'll be able to close this after the aex9 balance based on events is implemented and opted to replace dry-runs.

**Comment by thepiwo** [comment]
we will not start work on that for now, when event based handling is done we will re-consider to just close this
