### ISSUE TITLE
Microblock ordering

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#873]
https://mainnet.aeternity.io/mdw/blocks/28437

exposes the microblocks as object, thus the ordering coming from https://mainnet.aeternity.io/v3/generations/height/28437 is lost
can we either add some index attribute or think of another way to enable a consumer to restore the correct order implicitly (without iterating prev)

**Comment by thepiwo** [comment]
its already fixed in v2 https://mainnet.aeternity.io/mdw/v2/blocks?scope=gen:28437-28437

**Comment by profaneequinox03** [comment]
#629

**Comment by marc0olo** [comment]
> #629

what do you want to say with that? the support of AEX-141 has nothing to do with the microblock ordering 😅
