### ISSUE TITLE
Non-exposed balance change

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#881]
`ak_24jcHLTZQfsou7NvomRJ1hKEnjyNqbYSq2Az7DmyrAyUHPq8uR` changes balance on mainnet between height 34454 and 34455 but we don't seem to expose that currently

https://mainnet.aeternity.io/v3/accounts/ak_24jcHLTZQfsou7NvomRJ1hKEnjyNqbYSq2Az7DmyrAyUHPq8uR/height/34454
https://mainnet.aeternity.io/v3/accounts/ak_24jcHLTZQfsou7NvomRJ1hKEnjyNqbYSq2Az7DmyrAyUHPq8uR/height/34455

**Comment by thepiwo** [comment]
@sborrazas would you mind having a look at this, maybe this will also be interesting for activities?

**Comment by sborrazas** [comment]
It appears to be a refund from a non-responded oracle query. The query tx can be found here https://mainnet.aeternity.io/mdw/v2/txs/th_2gWt57ypjWAkWkJEAGueyKkLcpjnmpeRDEHvdAeVNwHoZJ59bu

**Comment by marc0olo** [comment]
might also be interesting for @seanhinde if not already covered somehow in the rosetta api 😅

**Comment by thepiwo** [comment]
maybe also fixed by #974

**Comment by thepiwo** [comment]
@sborrazas is this actually exposed in internal transfers or elsewhere now?

**Comment by sborrazas** [comment]
@thepiwo it's now part of internal transfers indeed

**Comment by thepiwo** [comment]
then we can close this as well
