### ISSUE TITLE
Update node version to 6.6+

### ISSUE THREAD

**Issue by sborrazas** [aeternity/ae_mdw#885]
This will require updating erlang/OTP together with elixir and the necessary dependencies

**Comment by thepiwo** [comment]
we also have #200 maybe we can try to update to latest elixir?

**Comment by thepiwo** [comment]
I don't see any otp23 elixir images, how would we handle that? https://hub.docker.com/_/elixir

**Comment by sborrazas** [comment]
Docker image [`elixir:1.11`](https://github.com/erlef/docker-elixir/blob/master/1.11/Dockerfile) uses [`erlang:23`](https://github.com/erlang/docker-erlang-otp/blob/master/23/Dockerfile) so we should probably go with that one.

feel free to close either GH issue, since it's a duplicate

**Comment by thepiwo** [comment]
lets keep it as two separate ones, just to keep in mind its distinct things but probably closed by the same PR

**Comment by thepiwo** [comment]
can be closed, right?

**Comment by sborrazas** [comment]
Yes
