### ISSUE TITLE
Improve unpaginated micro-blocks performance in /v2/blocks

### ISSUE THREAD

**Issue by thepiwo** [aeternity/ae_mdw#888]

**Comment by sborrazas** [comment]
Taking into account the info the explorer displays we should return the following info in these new endpoints (pseudo-JSON):

### GET /v3/blocks (paginated)
```
{
  "data": [
    {
      height: 1,
      hash: ..
      beneficiary: ...
      pow: ...
      microblocks_count: 23,
      transactions_count: 1234
  ]
}
```

### GET /v3/blocks/1
```
{
  hash: ..
  beneficiary: ...
  pow: ...
  microblocks_count: 23,
  transactions_count: 1234
}
```

### GET /v3/blocks/1/microblocks (paginated)
```
{
  "data": [
    {
      height: 1,
      mbi: 0,
      hash: ..
      beneficiary: ...
      pow: ...
      transactions_count: 57
  ]
}
```

### GET /v3/blocks/1/microblocks/0
```
{
  height: 1,
  mbi: 0,
  hash: ..
  beneficiary: ...
  pow: ...
  transactions_count: 57
}
```

Thoughts?

**Comment by thepiwo** [comment]
generally sounds good, lets check the overlap with core provided apis to not duplicate them to much

**Comment by sborrazas** [comment]
> 

It would basically end up being what the node returns + the counts. These counts would be the added value provided by the mdw

**Comment by sborrazas** [comment]
Following the [Node API Docs](https://api-docs.aeternity.io/) naming we should implement the following endpoints:

* `GET /generations`
* `GET /generations/:kbi_or_hash`
* `GET /generations/:kbi_or_hash/micro-blocks`
* `GET /generations/:kbi_or_hash/micro-blocks/:mbi_or_hash`
* `GET /generations/:kbi_or_hash/micro-blocks/:mbi_or_hash/txs`

Optionally, we can also include
* `GET /micro-blocks/:hash`
* `GET /micro-blocks/:hash/transactions`

When it exists, each of these resources should contain the counts for the nested resources (e.g. each key-block should contain the counts for micro-blocks and transactions).

**Comment by thepiwo** [comment]
@sborrazas why not just `/key-blocks` and `/micro-blocks`

**Comment by sborrazas** [comment]
@thepiwo not following, what would these two return? all of the key blocks and micro blocks paginated? How do you get a specific key block micro blocks?

**Comment by thepiwo** [comment]
I mean why `/generations/*` at all, not just `/key-blocks/*` and `/micro-blocks/*`

**Comment by thepiwo** [comment]
but seems like thats what you have implemented :+1:

**Comment by sborrazas** [comment]
@thepiwo yes, closing
