### ISSUE TITLE
Allow names filtered by owner to be ordered by expiration

### ISSUE THREAD

**Issue by sborrazas** [aeternity/ae_mdw#942]
Right now you get an error back: `invalid query: can't order by expiration when filtering by owner`

**Comment by marc0olo** [comment]
would be
- https://mainnet.aeternity.io/mdw/v2/names?owned_by=ak_25BWMx4An9mmQJNPSwJisiENek3bAGadze31Eetj4K4JJC8VQN&by=deactivation

I guess, right?

**Comment by marc0olo** [comment]
wondering a bit about the name change:
- https://github.com/aeternity/ae_mdw/pull/623

**Comment by sborrazas** [comment]
@marc0olo that's right! It would be deactivation, not expiration

**Comment by marc0olo** [comment]
ok what's the exact difference between?
- expiration
- deactivation

**Comment by sborrazas** [comment]
They are both the same, but since we're using the word `activation` for when a name becomes active, we're also using the word `deactivation` when it becomes inactive

**Comment by marc0olo** [comment]
just for clarification: `activation` comes from the fact that a `NameClaimTx` doesn't immediately activate the name in case of auctions.

personally I still prefer `expiration` over `deactivation` 🤔

**Comment by marc0olo** [comment]
makes absolute sense, thanks!

**Comment by sborrazas** [comment]
@thepiwo not yet

**Comment by thepiwo** [comment]
@sborrazas but now it is

**Comment by janmichek** [comment]
Seems like this is still not avialable. THe error message is the same. Is it released?
https://mainnet.aeternity.io/mdw/v2/names?owned_by=ak_25BWMx4An9mmQJNPSwJisiENek3bAGadze31Eetj4K4JJC8VQN&by=deactivation

**Comment by thepiwo** [comment]
@janmichek the fix is not released yet, will be ready in the next days
