### ISSUE TITLE
Add node transaction info to show if was successful or not

### ISSUE THREAD

**Issue by sborrazas** [aeternity/ae_mdw#956]
When returning an inner transaction info https://mainnet.aeternity.io/mdw/tx/th_2moRidJvFZweuQpbJXJsFryMPhqHG4rfEk1HWKGwauoHpzQQyw
we're not showing that the transaction itself is an internal transaction from a ga transaction.

This information should also be shown somehow https://mainnet.aeternity.io/v3/transactions/th_2moRidJvFZweuQpbJXJsFryMPhqHG4rfEk1HWKGwauoHpzQQyw/info

The node info is available for: 
`:contract_create_tx`, `:contract_call_tx`, `:ga_attach_tx`, `:ga_meta_tx` and `:channel_force_progress_tx`.

**Comment by jyeshe** [comment]
Generalizing to `:spend_tx` and other transactions:
https://mainnet.aeternity.io/mdw/v2/txs/th_WED5pREzRCN7ekZMWmxVCJe5z3L7fWadD3Y6EcY35RjZyJWhb
