### ISSUE TITLE
Oracle query created by Oracle.query calls don't have the right query_id

### ISSUE THREAD

**Issue by sborrazas** [aeternity/ae_mdw#974]
This is because the node doesn't return the query_id on those transactions, it always uses nonce=0

**Comment by sborrazas** [comment]
Fixed by #982

**Comment by jyeshe** [comment]
As discussed #982 wouldn't handle the cases where there is another transaction in the same micro-block before the one with "Oracle.query" but it was meant to be a temporary fix and a complete one was already provided by @sborrazas to the Node.
